import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { loadTargetEnv } from "./lib/env";

function main() {
  const target = process.argv[2] || "local";
  const { projectRef } = loadTargetEnv(target);

  const outputPath = path.join(
    process.cwd(),
    "wev-bulletin",
    "lib",
    "supabase",
    "database.types.ts",
  );

  let command = "supabase gen types typescript --schema public";

  if (target === "local") {
    command += " --local";
  } else {
    if (!projectRef || projectRef === "localhost" || projectRef === "127") {
      console.error(
        "✗ Error: Valid SUPABASE_PROJECT_REF is required to generate remote types.",
      );
      process.exit(1);
    }

    command += ` --project-id "${projectRef}"`;
  }

  try {
    console.log(`▶ Generating types using command: ${command}`);
    const typesHeader =
      "// Generated from the Supabase public schema.\n// Regenerate with: npm run types:supabase\n// Do not edit this file by hand.\n\n";

    const output = execSync(command, { encoding: "utf-8", stdio: "pipe" });

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, typesHeader + output);
    console.log(`✓ Wrote ${outputPath}`);
  } catch (error: any) {
    console.error("❌ Failed to generate types.");
    if (error.stdout) console.error(error.stdout);
    if (error.stderr) console.error(error.stderr);
    process.exit(1);
  }
}

main();
