import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { loadTargetEnv } from "./lib/env";
import { printExecError } from "./lib/error";

const FETCH_TIMEOUT_MS = 15_000;

async function fetchOpenApiSpec(
  baseUrl: string,
  anonKey: string,
): Promise<Record<string, unknown>> {
  const openApiUrl = `${baseUrl.replace(/\/+$/, "")}/rest/v1/`;
  console.log(`▶ Fetching OpenAPI spec from ${openApiUrl}...`);

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);

  try {
    const response = await fetch(openApiUrl, {
      signal: controller.signal,
      headers: {
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`,
        Accept: "application/openapi+json",
      },
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.json() as Promise<Record<string, unknown>>;
  } finally {
    clearTimeout(timeout);
  }
}

function extractDefinitionsSchema(spec: Record<string, unknown>): string {
  const definitions: Record<string, unknown> = (spec.definitions ?? {}) as Record<string, unknown>;
  const defNames = Object.keys(definitions);

  if (defNames.length === 0) {
    throw new Error("No definitions found in the OpenAPI spec.");
  }

  const schema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    definitions,
    type: "object",
    properties: Object.fromEntries(
      defNames.map((name) => [name, { $ref: `#/definitions/${name}` }]),
    ),
  };

  console.log(
    `✓ Extracted ${defNames.length} table definitions: ${defNames.join(", ")}`,
  );

  return JSON.stringify(schema, null, 2);
}

function findDatamodelCodegen(): string | null {
  const venvPath = path.join(
    process.cwd(),
    "wev-scraper",
    "venv",
    "bin",
    "datamodel-codegen",
  );
  if (fs.existsSync(venvPath)) {
    return venvPath;
  }
  try {
    execSync("which datamodel-codegen", { stdio: "ignore" });
    return "datamodel-codegen";
  } catch {
    return null;
  }
}

function generatePydanticModels(schemaPath: string, outputPath: string): void {
  const codegen = findDatamodelCodegen();
  if (!codegen) {
    throw new Error(
      "datamodel-codegen not found. Install it with: pip install datamodel-code-generator",
    );
  }
  const command = `"${codegen}" --input "${schemaPath}" --output "${outputPath}" --output-model-type pydantic_v2.BaseModel --input-file-type jsonschema`;

  execSync(command, { encoding: "utf-8", stdio: "inherit" });

  const modelsHeader =
    '"""\nGenerated from the Supabase public schema.\nRegenerate with: npm run types:python\nDo not edit this file by hand.\n"""\n\n';
  const existingContent = fs.readFileSync(outputPath, "utf-8");
  const cleaned = existingContent.replace(/^#\s+timestamp: .+\n/m, "");
  fs.writeFileSync(outputPath, modelsHeader + cleaned);

  console.log(`✓ Wrote ${outputPath}`);
}

async function main() {
  const target = process.argv[2] || "local";
  const config = loadTargetEnv(target);
  if (!config) process.exit(1);

  const tempDir = path.join(process.cwd(), "supabase", ".temp");
  const tempSpecPath = path.join(tempDir, "openapi.json");
  const tempSchemaPath = path.join(tempDir, "definitions_schema.json");
  const outputPath = path.join(
    process.cwd(),
    "wev-scraper",
    "lib",
    "database_models.py",
  );

  try {
    const spec = await fetchOpenApiSpec(config.supabaseUrl, config.anonKey);

    fs.mkdirSync(tempDir, { recursive: true });
    fs.writeFileSync(tempSpecPath, JSON.stringify(spec, null, 2));
    console.log(`✓ Saved OpenAPI spec to ${tempSpecPath}`);

    const schemaJson = extractDefinitionsSchema(spec);
    fs.writeFileSync(tempSchemaPath, schemaJson);

    generatePydanticModels(tempSchemaPath, outputPath);
  } catch (error: unknown) {
    printExecError(error);
    process.exit(1);
  } finally {
    for (const tmpFile of [tempSpecPath, tempSchemaPath]) {
      if (fs.existsSync(tmpFile)) fs.unlinkSync(tmpFile);
    }
  }
}

main();
