import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { loadTargetEnv } from "./lib/env";

const FETCH_TIMEOUT_MS = 15_000;

async function fetchOpenApiSpec(
  baseUrl: string,
  anonKey: string,
): Promise<string> {
  const openApiUrl = `${baseUrl}/rest/v1/`;
  console.log(`▶ Fetching OpenAPI spec from ${openApiUrl}...`);

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);

  try {
    const response = await fetch(openApiUrl, {
      signal: controller.signal,
      headers: {
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`,
        Accept: "application/openapi+json",
      },
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.text();
  } finally {
    clearTimeout(timeout);
  }
}

function extractDefinitionsSchema(specJson: string): string {
  const spec = JSON.parse(specJson);
  const definitions: Record<string, unknown> = spec.definitions ?? {};
  const defNames = Object.keys(definitions);

  if (defNames.length === 0) {
    throw new Error("No definitions found in the OpenAPI spec.");
  }

  const schema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    definitions,
    type: "object",
    properties: Object.fromEntries(
      defNames.map((name) => [name, { $ref: `#/definitions/${name}` }]),
    ),
  };

  console.log(
    `✓ Extracted ${defNames.length} table definitions: ${defNames.join(", ")}`,
  );

  return JSON.stringify(schema, null, 2);
}

function findDatamodelCodegen(): string {
  const venvPath = path.join(
    process.cwd(),
    "wev-scraper",
    "venv",
    "bin",
    "datamodel-codegen",
  );
  if (fs.existsSync(venvPath)) {
    return venvPath;
  }
  try {
    execSync("which datamodel-codegen", { stdio: "pipe" });
  } catch {
    console.error(
      "❌ datamodel-codegen not found. Install it with: pip install datamodel-code-generator",
    );
    process.exit(1);
  }
  return "datamodel-codegen";
}

function generatePydanticModels(schemaPath: string, outputPath: string): void {
  const codegen = findDatamodelCodegen();
  const command = `"${codegen}" --input "${schemaPath}" --output "${outputPath}" --output-model-type pydantic_v2.BaseModel --input-file-type jsonschema`;

  execSync(command, { encoding: "utf-8", stdio: "inherit" });

  const modelsHeader =
    '"""\nGenerated from the Supabase public schema.\nRegenerate with: npm run types:python\nDo not edit this file by hand.\n"""\n\n';
  const existingContent = fs.readFileSync(outputPath, "utf-8");
  const cleaned = existingContent.replace(/^#   timestamp: .+\n/m, "");
  fs.writeFileSync(outputPath, modelsHeader + cleaned);

  console.log(`✓ Wrote ${outputPath}`);
}

async function main() {
  const target = process.argv[2] || "local";
  const config = loadTargetEnv(target);
  if (!config) process.exit(1);

  const tempDir = path.join(process.cwd(), "supabase", ".temp");
  const tempSpecPath = path.join(tempDir, "openapi.json");
  const tempSchemaPath = path.join(tempDir, "definitions_schema.json");
  const outputPath = path.join(
    process.cwd(),
    "wev-scraper",
    "lib",
    "database_models.py",
  );

  try {
    const specJson = await fetchOpenApiSpec(config.supabaseUrl, config.anonKey);

    fs.mkdirSync(tempDir, { recursive: true });
    fs.writeFileSync(tempSpecPath, specJson);
    console.log(`✓ Saved OpenAPI spec to ${tempSpecPath}`);

    const schemaJson = extractDefinitionsSchema(specJson);
    fs.writeFileSync(tempSchemaPath, schemaJson);

    generatePydanticModels(tempSchemaPath, outputPath);
  } catch (error: unknown) {
    if (error instanceof Error) {
      const execErr = error as Error & {
        stdout?: string | Buffer;
        stderr?: string | Buffer;
      };
      console.error(`❌ ${error.message}`);
      if (execErr.stdout) console.error(String(execErr.stdout));
      if (execErr.stderr) console.error(String(execErr.stderr));
    }
    process.exit(1);
  } finally {
    for (const tmpFile of [tempSpecPath, tempSchemaPath]) {
      if (fs.existsSync(tmpFile)) fs.unlinkSync(tmpFile);
    }
  }
}

main();
