import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { loadTargetEnv } from "./lib/env";
import { printExecError } from "./lib/error";

/** Default local Supabase DB URL (config.toml db.port = 54322). */
const LOCAL_DB_URL =
  process.env.SUPABASE_DB_URL?.trim() ||
  process.env.DATABASE_URL?.trim() ||
  "postgresql://postgres:postgres@127.0.0.1:54322/postgres";

function stripPassword(dbUrl: string): { url: string; password?: string } {
  try {
    const parsedUrl = new URL(dbUrl);
    if (parsedUrl.protocol === "postgres:" || parsedUrl.protocol === "postgresql:") {
      if (parsedUrl.password) {
        let password = parsedUrl.password;
        try {
          password = decodeURIComponent(password);
        } catch {
          // ignore malformed percent encoding
        }
        parsedUrl.password = "";
        return { url: parsedUrl.toString(), password };
      }
      return { url: dbUrl };
    }
  } catch {
    // fallback for DSNs
  }

  let url = dbUrl;
  let password: string | undefined = undefined;

  const dsnPasswordMatch = url.match(/(?:^|\s)password\s*=\s*('([^']*)'|"([^"]*)"|(\S+))/i);
  if (dsnPasswordMatch) {
    password = dsnPasswordMatch[2] ?? dsnPasswordMatch[3] ?? dsnPasswordMatch[4];
    url = url.replace(dsnPasswordMatch[0], "").trim();
  }

  return { url, password };
}

function main() {
  const target = process.argv[2] || "local";
  const config = loadTargetEnv(target);
  if (!config) process.exit(1);

  const outputPath = path.join(
    process.cwd(),
    "wev-bulletin",
    "lib",
    "supabase",
    "database.types.ts",
  );

  let args = ["gen", "types", "typescript", "--schema", "public"];
  let execEnv = process.env;

  if (target === "local") {
    // --db-url talks to local Postgres directly (no Management API login).
    // Prefer this over --local so seed/typegen works without supabase login.
    const { url, password } = stripPassword(LOCAL_DB_URL);
    args.push("--db-url", url);
    if (password) {
      execEnv = { ...process.env, PGPASSWORD: password };
    }
  } else {
    const { projectRef } = config;
    if (!projectRef || projectRef === "localhost" || projectRef === "127") {
      console.error(
        "✗ Error: Valid SUPABASE_PROJECT_REF is required to generate remote types.",
      );
      process.exit(1);
    }

    args.push("--project-id", projectRef);
  }

  try {
    // Mask the password in the output command for safety if it were logged
    console.log(`▶ Generating types using command: supabase ${args.join(" ")}`);
    const typesHeader =
      "// Generated from the Supabase public schema.\n// Regenerate with: npm run types:supabase\n// Do not edit this file by hand.\n\n";

    const output = execFileSync("supabase", args, { encoding: "utf-8", stdio: "pipe", env: execEnv });

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, typesHeader + output);
    console.log(`✓ Wrote ${outputPath}`);
  } catch (error: unknown) {
    printExecError(error, "❌ Failed to generate types.");
    process.exit(1);
  }
}

main();
