-- Table: public.jobs
CREATE TABLE IF NOT EXISTS "public"."jobs" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "source_id" uuid NOT NULL,
    "job_title" text NOT NULL,
    "organization" text NOT NULL,
    "location" text,
    "listing_url" text NOT NULL,
    "description" text,
    "date_posted" text,
    "employment_type" text,
    "external_job_id" text,
    "extra" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "scraped_at" timestamp with time zone DEFAULT now() NOT NULL,
    "wage" text,
    "close_date" date,
    "municipality" text,
    "province" text,
    "is_remote" boolean,
    "summary" text,
    "sse_rating" text,
    "sse_details" jsonb,
    "is_sse" boolean DEFAULT false,
    "work_type" text DEFAULT 'office'::text NOT NULL,
    CONSTRAINT jobs_work_type_check CHECK (work_type = ANY (ARRAY['remote'::text, 'hybrid'::text, 'office'::text]))
);
ALTER TABLE "public"."jobs" OWNER TO "postgres";
COMMENT ON COLUMN "public"."jobs"."work_type" IS 'remote | hybrid | office';
ALTER TABLE ONLY "public"."jobs" ADD CONSTRAINT "jobs_pkey" PRIMARY KEY ("id");
-- Table: public.organizations
CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "name" text,
    "values" text,
    "type" text
);
ALTER TABLE "public"."organizations" OWNER TO "postgres";
ALTER TABLE "public"."organizations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organizations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."organizations" ADD CONSTRAINT "organizations_pkey" PRIMARY KEY ("id");
-- Table: public.profiles
CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" uuid NOT NULL,
    "full_name" text,
    "bio" text,
    "values" text[] DEFAULT '{}'::text[],
    "profile_photo_url" text,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);
ALTER TABLE "public"."profiles" OWNER TO "postgres";
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");
-- Table: public.scrape_runs
CREATE TABLE IF NOT EXISTS "public"."scrape_runs" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "started_at" timestamp with time zone DEFAULT now() NOT NULL,
    "ended_at" timestamp with time zone,
    "total_sources" integer DEFAULT 0 NOT NULL,
    "sources_with_errors" integer DEFAULT 0 NOT NULL,
    "total_jobs_found" integer DEFAULT 0 NOT NULL,
    "total_jobs_inserted" integer DEFAULT 0 NOT NULL,
    "status" text DEFAULT 'pending'::text NOT NULL,
    "errors" text,
    "jobs_found" integer DEFAULT 0,
    "jobs_added" integer DEFAULT 0,
    "run_at" timestamp without time zone DEFAULT now(),
    "source_id" uuid
);
ALTER TABLE "public"."scrape_runs" OWNER TO "postgres";
ALTER TABLE ONLY "public"."scrape_runs" ADD CONSTRAINT "scrape_runs_pkey" PRIMARY KEY ("id");
-- Table: public.sources
CREATE TABLE IF NOT EXISTS "public"."sources" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "name" text NOT NULL,
    "url" text NOT NULL,
    "active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."sources" OWNER TO "postgres";
ALTER TABLE ONLY "public"."sources" ADD CONSTRAINT "sources_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."sources" ADD CONSTRAINT "sources_url_key" UNIQUE ("url");
-- Table: public.user_roles
CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "user_id" uuid NOT NULL,
    "roles" text[] DEFAULT ARRAY['user'::text],
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);
ALTER TABLE "public"."user_roles" OWNER TO "postgres";
ALTER TABLE ONLY "public"."user_roles" ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("user_id");
