// Generated from the Supabase public schema.
// Regenerate with: npm run types:supabase
// Do not edit this file by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      bookmarks: {
        Row: {
          created_at: string
          job_id: string
          notes: string | null
          tags: string[]
          user_id: string
        }
        Insert: {
          created_at?: string
          job_id: string
          notes?: string | null
          tags?: string[]
          user_id: string
        }
        Update: {
          created_at?: string
          job_id?: string
          notes?: string | null
          tags?: string[]
          user_id?: string
        }
        Relationships: []
      }
      cities: {
        Row: {
          display_name: string
          id: number
          lat: number
          lng: number
          name: string
          province: string
          search_name: string | null
        }
        Insert: {
          display_name: string
          id?: number
          lat: number
          lng: number
          name: string
          province: string
          search_name?: string | null
        }
        Update: {
          display_name?: string
          id?: number
          lat?: number
          lng?: number
          name?: string
          province?: string
          search_name?: string | null
        }
        Relationships: []
      }
      esco_skills: {
        Row: {
          alternative_label_en: string[] | null
          alternative_label_fr: string[] | null
          concept_uri: string
          description_en: string | null
          description_fr: string | null
          embedding: string | null
          preferred_label_en: string | null
          preferred_label_fr: string | null
          reuse_level: string | null
          scope_note_en: string | null
          scope_note_fr: string | null
          skill_type: string | null
          updated_at: string | null
        }
        Insert: {
          alternative_label_en?: string[] | null
          alternative_label_fr?: string[] | null
          concept_uri: string
          description_en?: string | null
          description_fr?: string | null
          embedding?: string | null
          preferred_label_en?: string | null
          preferred_label_fr?: string | null
          reuse_level?: string | null
          scope_note_en?: string | null
          scope_note_fr?: string | null
          skill_type?: string | null
          updated_at?: string | null
        }
        Update: {
          alternative_label_en?: string[] | null
          alternative_label_fr?: string[] | null
          concept_uri?: string
          description_en?: string | null
          description_fr?: string | null
          embedding?: string | null
          preferred_label_en?: string | null
          preferred_label_fr?: string | null
          reuse_level?: string | null
          scope_note_en?: string | null
          scope_note_fr?: string | null
          skill_type?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      job_matches: {
        Row: {
          job_id: string
          location_score: number | null
          score: number
          shared_skills: string[] | null
          shared_values: string[]
          skill_score: number | null
          updated_at: string
          user_id: string
          value_score: number | null
          work_type_score: number | null
        }
        Insert: {
          job_id: string
          location_score?: number | null
          score: number
          shared_skills?: string[] | null
          shared_values?: string[]
          skill_score?: number | null
          updated_at?: string
          user_id: string
          value_score?: number | null
          work_type_score?: number | null
        }
        Update: {
          job_id?: string
          location_score?: number | null
          score?: number
          shared_skills?: string[] | null
          shared_values?: string[]
          skill_score?: number | null
          updated_at?: string
          user_id?: string
          value_score?: number | null
          work_type_score?: number | null
        }
        Relationships: []
      }
      job_skills: {
        Row: {
          created_at: string
          job_id: string
          score: number
          skill_id: string
          source: string
        }
        Insert: {
          created_at?: string
          job_id: string
          score: number
          skill_id: string
          source: string
        }
        Update: {
          created_at?: string
          job_id?: string
          score?: number
          skill_id?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_skills_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_skills_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "matched_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_skills_skill_id_fkey"
            columns: ["skill_id"]
            isOneToOne: false
            referencedRelation: "esco_skills"
            referencedColumns: ["concept_uri"]
          },
        ]
      }
      jobs: {
        Row: {
          close_date: string | null
          compensation_meta: Json | null
          date_posted: string | null
          description: string | null
          employment_type: string | null
          external_job_id: string | null
          extra: Json
          fts: unknown
          fts_en: unknown
          fts_fr: unknown
          geocode_accuracy_type: string | null
          has_compensation: boolean | null
          hours_per_week: number | null
          id: string
          is_remote: boolean | null
          is_sse: boolean | null
          job_title: string
          language: string
          lat: number | null
          listing_url: string
          lng: number | null
          location: string | null
          max_value: number | null
          min_value: number | null
          municipality: string | null
          organization: string
          province: string | null
          scraped_at: string
          skills: string[] | null
          skills_rated: Json | null
          source_id: string
          sse_details: Json | null
          sse_rating: string | null
          summary: string | null
          unit_text: string | null
          values: string[] | null
          values_rated: Json | null
          wage: string | null
          work_type: string
        }
        Insert: {
          close_date?: string | null
          compensation_meta?: Json | null
          date_posted?: string | null
          description?: string | null
          employment_type?: string | null
          external_job_id?: string | null
          extra?: Json
          fts?: unknown
          fts_en?: unknown
          fts_fr?: unknown
          geocode_accuracy_type?: string | null
          has_compensation?: boolean | null
          hours_per_week?: number | null
          id?: string
          is_remote?: boolean | null
          is_sse?: boolean | null
          job_title: string
          language?: string
          lat?: number | null
          listing_url: string
          lng?: number | null
          location?: string | null
          max_value?: number | null
          min_value?: number | null
          municipality?: string | null
          organization: string
          province?: string | null
          scraped_at?: string
          skills?: string[] | null
          skills_rated?: Json | null
          source_id: string
          sse_details?: Json | null
          sse_rating?: string | null
          summary?: string | null
          unit_text?: string | null
          values?: string[] | null
          values_rated?: Json | null
          wage?: string | null
          work_type?: string
        }
        Update: {
          close_date?: string | null
          compensation_meta?: Json | null
          date_posted?: string | null
          description?: string | null
          employment_type?: string | null
          external_job_id?: string | null
          extra?: Json
          fts?: unknown
          fts_en?: unknown
          fts_fr?: unknown
          geocode_accuracy_type?: string | null
          has_compensation?: boolean | null
          hours_per_week?: number | null
          id?: string
          is_remote?: boolean | null
          is_sse?: boolean | null
          job_title?: string
          language?: string
          lat?: number | null
          listing_url?: string
          lng?: number | null
          location?: string | null
          max_value?: number | null
          min_value?: number | null
          municipality?: string | null
          organization?: string
          province?: string | null
          scraped_at?: string
          skills?: string[] | null
          skills_rated?: Json | null
          source_id?: string
          sse_details?: Json | null
          sse_rating?: string | null
          summary?: string | null
          unit_text?: string | null
          values?: string[] | null
          values_rated?: Json | null
          wage?: string | null
          work_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: number
          name: string | null
          type: string | null
          values: string | null
        }
        Insert: {
          created_at?: string
          id?: number
          name?: string | null
          type?: string | null
          values?: string | null
        }
        Update: {
          created_at?: string
          id?: number
          name?: string | null
          type?: string | null
          values?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          bio: string | null
          created_at: string | null
          cv_import: Json | null
          full_name: string | null
          id: string
          lat: number | null
          lng: number | null
          location_display_name: string | null
          municipality: string | null
          profile_photo_url: string | null
          province: string | null
          skills: string[] | null
          skills_rated: Json | null
          updated_at: string | null
          values: string[] | null
          values_rated: Json | null
          work_types: string[] | null
        }
        Insert: {
          bio?: string | null
          created_at?: string | null
          cv_import?: Json | null
          full_name?: string | null
          id: string
          lat?: number | null
          lng?: number | null
          location_display_name?: string | null
          municipality?: string | null
          profile_photo_url?: string | null
          province?: string | null
          skills?: string[] | null
          skills_rated?: Json | null
          updated_at?: string | null
          values?: string[] | null
          values_rated?: Json | null
          work_types?: string[] | null
        }
        Update: {
          bio?: string | null
          created_at?: string | null
          cv_import?: Json | null
          full_name?: string | null
          id?: string
          lat?: number | null
          lng?: number | null
          location_display_name?: string | null
          municipality?: string | null
          profile_photo_url?: string | null
          province?: string | null
          skills?: string[] | null
          skills_rated?: Json | null
          updated_at?: string | null
          values?: string[] | null
          values_rated?: Json | null
          work_types?: string[] | null
        }
        Relationships: []
      }
      scrape_runs: {
        Row: {
          ended_at: string | null
          errors: string | null
          id: string
          jobs_added: number | null
          jobs_found: number | null
          run_at: string | null
          source_id: string | null
          sources_with_errors: number
          started_at: string
          status: string
          total_jobs_found: number
          total_jobs_inserted: number
          total_sources: number
        }
        Insert: {
          ended_at?: string | null
          errors?: string | null
          id?: string
          jobs_added?: number | null
          jobs_found?: number | null
          run_at?: string | null
          source_id?: string | null
          sources_with_errors?: number
          started_at?: string
          status?: string
          total_jobs_found?: number
          total_jobs_inserted?: number
          total_sources?: number
        }
        Update: {
          ended_at?: string | null
          errors?: string | null
          id?: string
          jobs_added?: number | null
          jobs_found?: number | null
          run_at?: string | null
          source_id?: string | null
          sources_with_errors?: number
          started_at?: string
          status?: string
          total_jobs_found?: number
          total_jobs_inserted?: number
          total_sources?: number
        }
        Relationships: [
          {
            foreignKeyName: "scrape_runs_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          active: boolean
          created_at: string
          id: string
          name: string
          url: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id?: string
          name: string
          url: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          name?: string
          url?: string
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string | null
          roles: string[] | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          roles?: string[] | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          roles?: string[] | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      matched_jobs: {
        Row: {
          close_date: string | null
          compensation_meta: Json | null
          date_posted: string | null
          description: string | null
          employment_type: string | null
          external_job_id: string | null
          extra: Json | null
          fts: unknown
          fts_en: unknown
          fts_fr: unknown
          geocode_accuracy_type: string | null
          has_compensation: boolean | null
          hours_per_week: number | null
          id: string | null
          is_remote: boolean | null
          is_sse: boolean | null
          job_title: string | null
          language: string | null
          lat: number | null
          listing_url: string | null
          lng: number | null
          location: string | null
          match_score: number | null
          max_value: number | null
          min_value: number | null
          municipality: string | null
          organization: string | null
          province: string | null
          scraped_at: string | null
          skill_score: number | null
          skills: string[] | null
          skills_rated: Json | null
          source: string | null
          source_id: string | null
          sse_details: Json | null
          sse_rating: string | null
          summary: string | null
          unit_text: string | null
          value_score: number | null
          values: string[] | null
          values_rated: Json | null
          wage: string | null
          work_type: string | null
        }
        Relationships: [
          {
            foreignKeyName: "jobs_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      annualize_v1: {
        Args: { actual_hours_per_week?: number; amount: number; unit: string }
        Returns: number
      }
      bulk_update_skill_embeddings: {
        Args: { updates: Json }
        Returns: undefined
      }
      earth: { Args: never; Returns: number }
      f_unaccent: { Args: { "": string }; Returns: string }
      location_score_for_pair: {
        Args: {
          p_job_accuracy_type: string
          p_job_lat: number
          p_job_lng: number
          p_job_municipality: string
          p_job_province: string
          p_job_work_type: string
          p_user_lat: number
          p_user_lng: number
          p_user_municipality: string
          p_user_province: string
          p_user_work_types: string[]
        }
        Returns: number
      }
      match_skills_by_embedding: {
        Args: { match_count?: number; query_embeddings: string[] }
        Returns: {
          concept_uri: string
          preferred_label_en: string
          preferred_label_fr: string
          query_index: number
          similarity: number
        }[]
      }
      rank_weight: { Args: { rank: number; total: number }; Returns: number }
      recalculate_matches_for_job: {
        Args: { p_job_id: string }
        Returns: undefined
      }
      recalculate_matches_for_user: {
        Args: { p_user_id: string }
        Returns: undefined
      }
      search_esco_skills: {
        Args: { p_limit?: number; p_locale?: string; p_query: string }
        Returns: {
          concept_uri: string
          definition: string
          matched_alias: string
          reuse_level: string
          scope_note: string
          score: number
          skill_type: string
          term: string
        }[]
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      unaccent: { Args: { "": string }; Returns: string }
      verify_user_password: { Args: { password: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

