#!/usr/bin/env python
"""Dry-run: same 10 Gemini+Tavily parity jobs, re-run with Groq+Tavily.

Loads job IDs + Gemini re-run results from:
  scripts/tavily_job_parity_5_gemini.{json,md}   (batch A)
  scripts/tavily_job_parity_5_gemini_b.{json,md} (batch B)

Forces Tavily-always grounding and Groq-only LLM (GEMINI + Cerebras unset
for the process so the chain cannot fall through to Gemini).

Never writes to Supabase. Does not patch prod.

Usage:
  CONFIRM_PROD_RUN=YES ./venv/bin/python scripts/tavily_job_parity_10_groq.py --prod
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from settings import ensure_env_loaded, load_db_credentials_only  # noqa: E402
from utils.prod_env import (  # noqa: E402
    confirm_prod_run,
    mark_prod_confirmed,
    resolve_prod_env_path,
)

LOG_PATH = Path("/tmp/tavily_job_parity_10_groq.log")
REPORT_MD = _ROOT / "scripts" / "tavily_job_parity_10_groq.md"
REPORT_JSON = _ROOT / "scripts" / "tavily_job_parity_10_groq.json"

GEMINI_A_JSON = _ROOT / "scripts" / "tavily_job_parity_5_gemini.json"
GEMINI_B_JSON = _ROOT / "scripts" / "tavily_job_parity_5_gemini_b.json"

STABLE_FIELDS = ("sse_rating", "is_sse")
PLACEHOLDER_REASONING = "Generated by unified processor"


def _configure_report_paths(tag: str | None) -> None:
    """Optionally write to *_v2.md / *_v2.json (and matching log)."""
    global LOG_PATH, REPORT_MD, REPORT_JSON
    if not tag:
        return
    safe = tag.strip().lstrip("_")
    if not safe:
        return
    REPORT_MD = _ROOT / "scripts" / f"tavily_job_parity_10_groq_{safe}.md"
    REPORT_JSON = _ROOT / "scripts" / f"tavily_job_parity_10_groq_{safe}.json"
    LOG_PATH = Path(f"/tmp/tavily_job_parity_10_groq_{safe}.log")

ensure_env_loaded()
if "--prod" in sys.argv[1:]:
    confirm_prod_run(full_prod=False)
    mark_prod_confirmed()
    applied = load_db_credentials_only(resolve_prod_env_path(Path(__file__)))
    os.environ["USE_PROD_DB"] = "1"
    print(f"PRODUCTION DB (read-only); keys={', '.join(applied) or '(none)'}")

# Force Groq-only: strip Gemini (+ Cerebras fallback) after env load so
# SSEFallbackProvider builds groq-only chain. Keys remain in parent shell.
_GEMINI_WAS_SET = bool((os.environ.get("GEMINI_API_KEY") or "").strip())
_CEREBRAS_WAS_SET = bool((os.environ.get("CEREBRAS_API_KEY") or "").strip())
for _k in (
    "GEMINI_API_KEY",
    "GOOGLE_API_KEY",
    "GOOGLE_GENAI_API_KEY",
    "CEREBRAS_API_KEY",
):
    os.environ.pop(_k, None)

from llm.gemini_fallback import (  # noqa: E402
    SSEFallbackProvider,
    _use_google_search_grounding,
)
from llm.tavily_grounding import (  # noqa: E402
    entity_require_terms,
    fetch_tavily_evidence,
    is_tavily_available,
    require_tavily,
)
from utils.db import reset_supabase_client_cache, supabase  # noqa: E402
from utils.sse_classifier import SSEClassificationError, SSEClassifier  # noqa: E402
from utils.sse_job_guards import apply_job_sse_guards  # noqa: E402
from utils.sse_prompts import (  # noqa: E402
    SSE_JOB_SYSTEM_PROMPT,
    get_sse_classification_prompt,
)


def _early_out_tag() -> str | None:
    argv = sys.argv[1:]
    for i, a in enumerate(argv):
        if a == "--out-tag" and i + 1 < len(argv):
            return argv[i + 1]
        if a.startswith("--out-tag="):
            return a.split("=", 1)[1]
    return None


_configure_report_paths(_early_out_tag())

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_PATH, mode="w"),
    ],
)
logger = logging.getLogger("tavily_job_parity_10_groq")

JOB_SELECT = (
    "id,job_title,organization,organization_id,location,municipality,province,"
    "wage,description,summary,sse_rating,is_sse,language,values,listing_url,"
    "date_posted,scraped_at,sse_details"
)


def _parse_details(raw: Any) -> dict:
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw.strip():
        try:
            parsed = json.loads(raw)
            return parsed if isinstance(parsed, dict) else {}
        except json.JSONDecodeError:
            return {"raw": raw}
    return {}


def _host(url: str) -> str | None:
    try:
        host = urlparse(url).netloc.lower()
    except Exception:
        return None
    if host.startswith("www."):
        host = host[4:]
    return host or None


def _yesno(v: Any) -> str:
    if v is True:
        return "yes"
    if v is False:
        return "NO"
    return "—"


def _load_gemini_priors() -> dict[str, dict[str, Any]]:
    """job_id -> {batch, title, org, prod_*, gemini_*} from prior reports."""
    out: dict[str, dict[str, Any]] = {}
    for path, batch in ((GEMINI_A_JSON, "A"), (GEMINI_B_JSON, "B")):
        if not path.is_file():
            raise FileNotFoundError(f"Missing prior Gemini report: {path}")
        data = json.loads(path.read_text())
        for row in data.get("jobs") or []:
            jid = row.get("job_id")
            if not jid:
                continue
            prod = row.get("prod") or {}
            rerun = row.get("rerun") or {}
            out[str(jid)] = {
                "batch": batch,
                "title": row.get("title") or prod.get("job_title"),
                "organization": row.get("organization") or prod.get("organization"),
                "prod_sse_rating": prod.get("sse_rating"),
                "prod_is_sse": prod.get("is_sse"),
                "prod_org_type": prod.get("type"),
                "gemini_sse_rating": rerun.get("sse_rating"),
                "gemini_is_sse": rerun.get("is_sse"),
                "gemini_provider": rerun.get("provider"),
                "gemini_confidence": rerun.get("confidence"),
                "gemini_reasoning": rerun.get("reasoning"),
                "gemini_tavily_hosts": rerun.get("tavily_hosts") or [],
                "gemini_divergence_label": row.get("divergence_label"),
                "baseline_quality": (prod.get("baseline_quality") or {}).get("quality"),
            }
    return out


def fetch_jobs_by_ids(job_ids: list[str]) -> list[dict]:
    rows = (
        supabase.table("jobs")
        .select(JOB_SELECT)
        .in_("id", job_ids)
        .execute()
        .data
        or []
    )
    by_id = {str(r["id"]): r for r in rows}
    missing = [jid for jid in job_ids if jid not in by_id]
    if missing:
        raise RuntimeError(f"Jobs not found in prod: {missing}")
    # Preserve prior report order (A then B)
    return [by_id[jid] for jid in job_ids]


def _org_type_map(org_ids: list[Any]) -> dict[Any, dict]:
    ids = [i for i in org_ids if i is not None]
    if not ids:
        return {}
    rows = (
        supabase.table("organizations")
        .select("id,name,type,sse_rating,is_sse")
        .in_("id", ids)
        .execute()
        .data
        or []
    )
    return {r["id"]: r for r in rows}


def classify_job_tavily_always(clf: SSEClassifier, job: dict) -> dict[str, Any]:
    org_name = job.get("organization") or "Unknown"
    job_title = job.get("job_title") or "Unknown"
    location = job.get("location") or "Unknown"
    salary = job.get("wage") or "Not specified"
    description = (job.get("description") or "").strip()
    posted_date = str(job.get("date_posted") or datetime.now(timezone.utc).isoformat())
    listing_url = job.get("listing_url") or ""

    if not description:
        raise SSEClassificationError("Job description required for parity re-run")

    prompt = get_sse_classification_prompt(
        org_name=org_name,
        job_title=job_title,
        location=location,
        salary=salary,
        job_description=description,
        posted_date=posted_date,
    )

    search_terms = f'"{org_name}"'
    if location and location != "Unknown":
        search_terms += f' "{location}"'
    search_query = f"{search_terms} official website mission governance"
    require_terms = entity_require_terms(org_name) or None

    evidence = fetch_tavily_evidence(search_query, require_terms=require_terms)
    tavily_urls = list(evidence.urls or [])
    tavily_hosts = sorted({h for u in tavily_urls if (h := _host(u))})

    t0 = time.perf_counter()
    last_error = ""
    for attempt in range(2):
        try:
            response_text = clf._call_provider_with_retry(
                provider=clf.provider,
                prompt=prompt,
                system=SSE_JOB_SYSTEM_PROMPT,
                task="sse",
                temperature=0,
                search_query=search_query,
                retries=0,
                require_terms=require_terms,
                use_grounding=True,  # tavily-always
            )
        except SSEClassificationError as exc:
            last_error = str(exc)
            logger.warning("provider error attempt %d/2: %s", attempt + 1, last_error)
            if "429" in last_error or "quota" in last_error.lower():
                time.sleep(8)
            continue

        parsed, parse_error = clf._safe_parse_sse_response(
            response_text, job_title, org_name
        )
        if parsed is not None:
            parsed = apply_job_sse_guards(
                parsed,
                salary=salary,
                description=description,
            )
            rating = parsed["rating"]
            provider_name = getattr(clf.provider, "current_model", None) or getattr(
                clf.provider, "_last_successful", None
            )
            return {
                "sse_rating": rating,
                "is_sse": rating in ("strong_yes", "weak_yes"),
                "type": None,
                "confidence": parsed.get("confidence"),
                "reasoning": parsed.get("reasoning"),
                "must_haves_met": parsed.get("must_haves_met") or [],
                "nice_to_haves_met": parsed.get("nice_to_haves_met") or [],
                "flags": parsed.get("flags") or [],
                "classified_at": parsed.get("classified_at"),
                "provider": provider_name,
                "listing_url": listing_url,
                "search_query": search_query,
                "tavily_always": True,
                "tavily_urls": tavily_urls,
                "tavily_hosts": tavily_hosts,
                "tavily_evidence_chars": len(evidence.text or ""),
                "elapsed_s": round(time.perf_counter() - t0, 2),
                "error": None,
            }
        last_error = parse_error or "parse error"
        logger.warning("parse error attempt %d/2: %s", attempt + 1, last_error)

    return {
        "error": last_error or "classification failed",
        "elapsed_s": round(time.perf_counter() - t0, 2),
        "tavily_always": True,
        "tavily_urls": tavily_urls,
        "tavily_hosts": tavily_hosts,
        "tavily_evidence_chars": len(evidence.text or ""),
        "type": None,
    }


def _match_rates(pairs: list[tuple[Any, Any]]) -> dict[str, Any]:
    n = len(pairs)
    m = sum(1 for a, b in pairs if a == b and a is not None)
    return {
        "n": n,
        "matches": m,
        "pct": f"{(100.0 * m / n):.0f}" if n else "0",
        "frac": f"{m}/{n}",
    }


def write_report(payload: dict) -> None:
    setup = payload.get("setup") or {}
    rates = payload.get("match_rates") or {}
    lines: list[str] = []
    tag = setup.get("out_tag")
    title = "Tavily-always job parity: Groq vs prod vs Gemini (10 jobs)"
    if tag:
        title += f" — {tag}"
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"Generated: `{payload['generated_at']}`")
    lines.append("")
    if tag:
        lines.append(
            f"Re-run after shared prompt/guard tightenings (`--out-tag {tag}`). "
            "Compare **groq_v2** vs Gemini+Tavily vs prod."
        )
        lines.append("")
    lines.append(
        "Same 10 jobs as Gemini+Tavily batches A+B "
        "(`scripts/tavily_job_parity_5_gemini.md`, "
        "`scripts/tavily_job_parity_5_gemini_b.md`), re-run with **Groq + Tavily**."
    )
    lines.append("")
    lines.append("## Setup")
    lines.append("")
    lines.append(
        f"- **SSE chain:** `{setup.get('provider_chain')}` "
        f"(Groq-only confirmed: `{setup.get('groq_only')}`)"
    )
    lines.append(
        f"- **`GEMINI_API_KEY` in process:** `{setup.get('gemini_key_in_process')}` "
        f"(was present in .env before unset: `{setup.get('gemini_was_in_env')}`)"
    )
    lines.append(
        f"- **`CEREBRAS_API_KEY` in process:** `{setup.get('cerebras_key_in_process')}` "
        f"(was present before unset: `{setup.get('cerebras_was_in_env')}`)"
    )
    lines.append(
        f"- **`USE_GOOGLE_SEARCH_GROUNDING`:** `{setup.get('use_google_search_grounding')}` "
        "— **off (expected)**; Tavily replaces Gemini-native Google Search grounding."
    )
    lines.append(f"- **Tavily available:** `{setup.get('tavily_available')}`")
    lines.append(
        "- Mode: force `use_grounding=True` + employer search query (tavily-always); "
        "dry-run only — **no DB writes**."
    )
    lines.append("")
    lines.append("## Headline rates")
    lines.append("")
    gp = rates.get("groq_vs_prod") or {}
    gg = rates.get("groq_vs_gemini") or {}
    gmp = rates.get("gemini_vs_prod") or {}
    lines.append(
        f"- **Groq vs prod:** rating `{gp.get('sse_rating', {}).get('frac')}` "
        f"({gp.get('sse_rating', {}).get('pct')}%) · "
        f"is_sse `{gp.get('is_sse', {}).get('frac')}` "
        f"({gp.get('is_sse', {}).get('pct')}%) · "
        f"both `{gp.get('both', {}).get('frac')}` "
        f"({gp.get('both', {}).get('pct')}%)"
    )
    lines.append(
        f"- **Groq vs Gemini:** rating `{gg.get('sse_rating', {}).get('frac')}` "
        f"({gg.get('sse_rating', {}).get('pct')}%) · "
        f"is_sse `{gg.get('is_sse', {}).get('frac')}` "
        f"({gg.get('is_sse', {}).get('pct')}%) · "
        f"both `{gg.get('both', {}).get('frac')}` "
        f"({gg.get('both', {}).get('pct')}%)"
    )
    lines.append(
        f"- **Gemini vs prod (prior):** rating `{gmp.get('sse_rating', {}).get('frac')}` "
        f"({gmp.get('sse_rating', {}).get('pct')}%) · "
        f"is_sse `{gmp.get('is_sse', {}).get('frac')}` "
        f"({gmp.get('is_sse', {}).get('pct')}%) · "
        f"both `{gmp.get('both', {}).get('frac')}` "
        f"({gmp.get('both', {}).get('pct')}%) — reminder: prior A+B was **6/10** rating."
    )
    lines.append("")
    lines.append(f"**{payload.get('headline')}**")
    lines.append("")
    lines.append("## Summary table")
    lines.append("")
    lines.append(
        "| # | Batch | Job | Org | Prod rating / is_sse | "
        "Gemini+T | Groq+T | G↔prod | Gr↔prod | Gr↔Gem | Provider | Elapsed |"
    )
    lines.append(
        "|---|-------|-----|-----|----------------------|"
        "----------|--------|--------|---------|--------|----------|---------|"
    )
    for i, row in enumerate(payload.get("jobs") or [], 1):
        prod = row.get("prod") or {}
        gem = row.get("gemini") or {}
        groq = row.get("rerun") or {}
        flags = row.get("match_flags") or {}
        title = (row.get("title") or "")[:36]
        org = (row.get("organization") or "")[:28]
        if len(row.get("title") or "") > 36:
            title += "..."
        if len(row.get("organization") or "") > 28:
            org += "..."
        lines.append(
            f"| {i} | {row.get('batch')} | {title} | {org} | "
            f"`{prod.get('sse_rating')}` / {_yesno(prod.get('is_sse'))} | "
            f"`{gem.get('sse_rating')}` / {_yesno(gem.get('is_sse'))} | "
            f"`{groq.get('sse_rating')}` / {_yesno(groq.get('is_sse'))} | "
            f"{'yes' if flags.get('gemini_vs_prod') else 'NO'} | "
            f"{'yes' if flags.get('groq_vs_prod') else 'NO'} | "
            f"{'yes' if flags.get('groq_vs_gemini') else 'NO'} | "
            f"`{groq.get('provider') or '—'}` | "
            f"{groq.get('elapsed_s') if groq.get('elapsed_s') is not None else '—'}s |"
        )
    lines.append("")
    lines.append("Match flags are **both** `sse_rating` + `is_sse` (structural).")
    lines.append("")
    lines.append("## Verdict")
    lines.append("")
    lines.append(payload.get("verdict") or "")
    lines.append("")
    lines.append("### Notable flips")
    lines.append("")
    flips = payload.get("notable_flips") or []
    if not flips:
        lines.append("- None — Groq matched Gemini on all structural fields.")
    else:
        for f in flips:
            lines.append(f"- {f}")
    lines.append("")
    lines.append("## Per-job detail")
    lines.append("")
    for i, row in enumerate(payload.get("jobs") or [], 1):
        prod = row.get("prod") or {}
        gem = row.get("gemini") or {}
        groq = row.get("rerun") or {}
        flags = row.get("match_flags") or {}
        lines.append(f"## Job {i}: `{row.get('job_id')}` (batch {row.get('batch')})")
        lines.append("")
        lines.append(f"- **Title:** {row.get('title')}")
        lines.append(
            f"- **Org:** {row.get('organization')} "
            f"(org_type=`{prod.get('org_type')}`)"
        )
        lines.append(f"- **Baseline quality (prior):** {prod.get('baseline_quality')}")
        lines.append("")
        lines.append("| Field | Prod | Gemini+Tavily | Groq+Tavily |")
        lines.append("|-------|------|---------------|-------------|")
        for field in ("sse_rating", "is_sse"):
            lines.append(
                f"| `{field}` | `{prod.get(field)}` | `{gem.get(field)}` | "
                f"`{groq.get(field)}` |"
            )
        lines.append(
            f"| provider | — | `{gem.get('provider')}` | `{groq.get('provider')}` |"
        )
        lines.append("")
        lines.append(
            f"- **Match flags:** groq↔prod=`{flags.get('groq_vs_prod')}` · "
            f"groq↔gemini=`{flags.get('groq_vs_gemini')}` · "
            f"gemini↔prod=`{flags.get('gemini_vs_prod')}` "
            f"(rating-only: gr↔prod=`{flags.get('groq_vs_prod_rating')}` · "
            f"gr↔gem=`{flags.get('groq_vs_gemini_rating')}`)"
        )
        if groq.get("error"):
            lines.append(f"- **ERROR:** {groq['error']}")
        else:
            reason = (groq.get("reasoning") or "").replace("\n", " ")
            if len(reason) > 500:
                reason = reason[:497] + "..."
            lines.append(f"- **Groq reasoning:** {reason}")
            hosts = groq.get("tavily_hosts") or []
            lines.append(
                f"- **Tavily hosts:** {', '.join(hosts) or '—'} "
                f"({groq.get('tavily_evidence_chars') or 0} chars)"
            )
        lines.append("")

    lines.append("## Failures / infra")
    lines.append("")
    fails = payload.get("failures") or []
    if fails:
        for f in fails:
            lines.append(f"- {f}")
    else:
        lines.append("- None observed.")
    lines.append("")
    lines.append(f"Log: `{LOG_PATH}`")
    lines.append(f"JSON: `{REPORT_JSON}`")
    lines.append(f"Script: `{Path(__file__).resolve()}`")
    lines.append("")

    REPORT_MD.write_text("\n".join(lines) + "\n")
    REPORT_JSON.write_text(json.dumps(payload, indent=2, default=str) + "\n")
    logger.info("Wrote %s and %s", REPORT_MD, REPORT_JSON)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prod", action="store_true", help="Read from production DB")
    parser.add_argument("--delay", type=float, default=12.0)
    parser.add_argument(
        "--out-tag",
        default=None,
        help="Write scripts/tavily_job_parity_10_groq_<tag>.{md,json} (e.g. v2)",
    )
    parser.add_argument(
        "--only-job-ids",
        default=None,
        help="Comma-separated job IDs to run (subset of the fixed 10)",
    )
    args = parser.parse_args()
    if args.out_tag:
        _configure_report_paths(args.out_tag)

    reset_supabase_client_cache()

    priors = _load_gemini_priors()
    job_ids = list(priors.keys())
    if args.only_job_ids:
        wanted = {x.strip() for x in args.only_job_ids.split(",") if x.strip()}
        job_ids = [j for j in job_ids if j in wanted]
        missing = wanted - set(job_ids)
        if missing:
            logger.error("Unknown job ids (not in Gemini priors): %s", sorted(missing))
            raise SystemExit(2)
    if not args.only_job_ids and len(job_ids) != 10:
        logger.error("Expected 10 prior jobs, got %d from Gemini reports", len(job_ids))
        raise SystemExit(2)

    gemini_in_proc = bool((os.environ.get("GEMINI_API_KEY") or "").strip())
    cerebras_in_proc = bool((os.environ.get("CEREBRAS_API_KEY") or "").strip())
    google_search_on = _use_google_search_grounding()
    tavily_ok = is_tavily_available()

    probe = SSEFallbackProvider()
    chain_names = [n for n, _ in probe._providers]
    groq_only = chain_names == ["groq"]
    groq_first = bool(chain_names) and chain_names[0] == "groq"
    logger.info(
        "setup gemini_in_proc=%s (was=%s) cerebras_in_proc=%s (was=%s) "
        "google_search=%s tavily=%s chain=%s groq_only=%s",
        gemini_in_proc,
        _GEMINI_WAS_SET,
        cerebras_in_proc,
        _CEREBRAS_WAS_SET,
        google_search_on,
        tavily_ok,
        " → ".join(chain_names),
        groq_only,
    )
    if gemini_in_proc or any(n.startswith("gemini") for n in chain_names):
        logger.error("Gemini still available — aborting (want Groq-only)")
        raise SystemExit(2)
    if not groq_first:
        logger.error("Groq not first in chain: %s", chain_names)
        raise SystemExit(2)
    if not groq_only:
        logger.warning(
            "Chain is not groq-only (%s) — continuing but providers beyond groq may fire",
            chain_names,
        )

    try:
        require_tavily()
    except Exception as exc:
        logger.error("require_tavily failed: %s", exc)
        raise SystemExit(2) from exc

    try:
        clf = SSEClassifier()
    except SSEClassificationError as exc:
        logger.error("SSEClassifier init failed: %s", exc)
        raise SystemExit(2) from exc

    jobs = fetch_jobs_by_ids(job_ids)
    org_map = _org_type_map([j.get("organization_id") for j in jobs])
    logger.info("Selected %d fixed jobs for Groq/Tavily parity", len(jobs))

    reports: list[dict] = []
    failures: list[str] = []
    providers_used: list[str] = []

    for i, job in enumerate(jobs):
        if i:
            time.sleep(args.delay)
        jid = str(job["id"])
        prior = priors[jid]
        org_info = org_map.get(job.get("organization_id")) or {}
        details = _parse_details(job.get("sse_details"))
        prod = {
            "sse_rating": job.get("sse_rating"),
            "is_sse": job.get("is_sse"),
            "org_type": org_info.get("type") or prior.get("prod_org_type"),
            "baseline_quality": prior.get("baseline_quality"),
            "reasoning": details.get("reasoning"),
        }
        # Prefer live prod; fall back to prior snapshot if somehow null
        if prod["sse_rating"] is None:
            prod["sse_rating"] = prior.get("prod_sse_rating")
        if prod["is_sse"] is None:
            prod["is_sse"] = prior.get("prod_is_sse")

        gemini = {
            "sse_rating": prior.get("gemini_sse_rating"),
            "is_sse": prior.get("gemini_is_sse"),
            "provider": prior.get("gemini_provider"),
            "confidence": prior.get("gemini_confidence"),
            "reasoning": prior.get("gemini_reasoning"),
            "tavily_hosts": prior.get("gemini_tavily_hosts"),
            "divergence_label": prior.get("gemini_divergence_label"),
        }

        logger.info(
            "=== JOB %d/%d [%s] %s @ %s (prod=%s gemini=%s) ===",
            i + 1,
            len(jobs),
            prior.get("batch"),
            job.get("job_title"),
            job.get("organization"),
            prod.get("sse_rating"),
            gemini.get("sse_rating"),
        )
        try:
            rerun = classify_job_tavily_always(clf, job)
        except Exception as exc:
            logger.error("Unhandled: %s\n%s", exc, traceback.format_exc())
            rerun = {
                "error": str(exc),
                "elapsed_s": None,
                "tavily_always": True,
                "type": None,
            }
            failures.append(f"job {jid}: {exc}")

        if rerun.get("error"):
            err = str(rerun["error"])
            failures.append(f"job {jid}: {err}")
            if "429" in err or "quota" in err.lower() or "rate" in err.lower():
                failures.append(f"likely rate-limit/429 on job {jid}")
                time.sleep(15)

        if rerun.get("provider"):
            providers_used.append(str(rerun["provider"]))
            if str(rerun["provider"]).startswith("gemini"):
                failures.append(
                    f"UNEXPECTED gemini provider on job {jid}: {rerun['provider']}"
                )

        rating_gp = (not rerun.get("error")) and (
            prod.get("sse_rating") == rerun.get("sse_rating")
        )
        is_sse_gp = (not rerun.get("error")) and (
            prod.get("is_sse") == rerun.get("is_sse")
        )
        rating_gg = (not rerun.get("error")) and (
            gemini.get("sse_rating") == rerun.get("sse_rating")
        )
        is_sse_gg = (not rerun.get("error")) and (
            gemini.get("is_sse") == rerun.get("is_sse")
        )
        rating_gmp = prod.get("sse_rating") == gemini.get("sse_rating")
        is_sse_gmp = prod.get("is_sse") == gemini.get("is_sse")

        flags = {
            "groq_vs_prod_rating": rating_gp,
            "groq_vs_prod_is_sse": is_sse_gp,
            "groq_vs_prod": rating_gp and is_sse_gp,
            "groq_vs_gemini_rating": rating_gg,
            "groq_vs_gemini_is_sse": is_sse_gg,
            "groq_vs_gemini": rating_gg and is_sse_gg,
            "gemini_vs_prod_rating": rating_gmp,
            "gemini_vs_prod_is_sse": is_sse_gmp,
            "gemini_vs_prod": rating_gmp and is_sse_gmp,
        }

        logger.info(
            "  groq rating=%s is_sse=%s provider=%s elapsed=%ss "
            "gr↔prod=%s gr↔gem=%s",
            rerun.get("sse_rating"),
            rerun.get("is_sse"),
            rerun.get("provider"),
            rerun.get("elapsed_s"),
            flags["groq_vs_prod"],
            flags["groq_vs_gemini"],
        )

        reports.append(
            {
                "job_id": jid,
                "batch": prior.get("batch"),
                "title": job.get("job_title") or prior.get("title"),
                "organization": job.get("organization") or prior.get("organization"),
                "prod": prod,
                "gemini": gemini,
                "rerun": rerun,
                "match_flags": flags,
            }
        )

    n = len(reports)
    ok = [r for r in reports if not (r.get("rerun") or {}).get("error")]

    groq_vs_prod_rating = _match_rates(
        [
            ((r.get("prod") or {}).get("sse_rating"), (r.get("rerun") or {}).get("sse_rating"))
            for r in ok
        ]
    )
    groq_vs_prod_is_sse = _match_rates(
        [
            ((r.get("prod") or {}).get("is_sse"), (r.get("rerun") or {}).get("is_sse"))
            for r in ok
        ]
    )
    groq_vs_prod_both = _match_rates(
        [
            (
                (
                    (r.get("prod") or {}).get("sse_rating"),
                    (r.get("prod") or {}).get("is_sse"),
                ),
                (
                    (r.get("rerun") or {}).get("sse_rating"),
                    (r.get("rerun") or {}).get("is_sse"),
                ),
            )
            for r in ok
        ]
    )

    groq_vs_gem_rating = _match_rates(
        [
            (
                (r.get("gemini") or {}).get("sse_rating"),
                (r.get("rerun") or {}).get("sse_rating"),
            )
            for r in ok
        ]
    )
    groq_vs_gem_is_sse = _match_rates(
        [
            ((r.get("gemini") or {}).get("is_sse"), (r.get("rerun") or {}).get("is_sse"))
            for r in ok
        ]
    )
    groq_vs_gem_both = _match_rates(
        [
            (
                (
                    (r.get("gemini") or {}).get("sse_rating"),
                    (r.get("gemini") or {}).get("is_sse"),
                ),
                (
                    (r.get("rerun") or {}).get("sse_rating"),
                    (r.get("rerun") or {}).get("is_sse"),
                ),
            )
            for r in ok
        ]
    )

    # Gemini vs prod from priors (all 10, independent of groq success)
    gem_vs_prod_rating = _match_rates(
        [
            (
                (r.get("prod") or {}).get("sse_rating"),
                (r.get("gemini") or {}).get("sse_rating"),
            )
            for r in reports
        ]
    )
    gem_vs_prod_is_sse = _match_rates(
        [
            ((r.get("prod") or {}).get("is_sse"), (r.get("gemini") or {}).get("is_sse"))
            for r in reports
        ]
    )
    gem_vs_prod_both = _match_rates(
        [
            (
                (
                    (r.get("prod") or {}).get("sse_rating"),
                    (r.get("prod") or {}).get("is_sse"),
                ),
                (
                    (r.get("gemini") or {}).get("sse_rating"),
                    (r.get("gemini") or {}).get("is_sse"),
                ),
            )
            for r in reports
        ]
    )

    match_rates = {
        "n": n,
        "n_ok": len(ok),
        "groq_vs_prod": {
            "sse_rating": groq_vs_prod_rating,
            "is_sse": groq_vs_prod_is_sse,
            "both": groq_vs_prod_both,
        },
        "groq_vs_gemini": {
            "sse_rating": groq_vs_gem_rating,
            "is_sse": groq_vs_gem_is_sse,
            "both": groq_vs_gem_both,
        },
        "gemini_vs_prod": {
            "sse_rating": gem_vs_prod_rating,
            "is_sse": gem_vs_prod_is_sse,
            "both": gem_vs_prod_both,
        },
    }

    notable_flips: list[str] = []
    for r in reports:
        groq = r.get("rerun") or {}
        gem = r.get("gemini") or {}
        prod = r.get("prod") or {}
        flags = r.get("match_flags") or {}
        title = r.get("title") or r.get("job_id")
        if groq.get("error"):
            notable_flips.append(f"**error** — {title}: {groq['error']}")
            continue
        if not flags.get("groq_vs_gemini"):
            notable_flips.append(
                f"**groq≠gemini** — {title} @ {r.get('organization')}: "
                f"gemini=`{gem.get('sse_rating')}`/{gem.get('is_sse')} → "
                f"groq=`{groq.get('sse_rating')}`/{groq.get('is_sse')} "
                f"(prod=`{prod.get('sse_rating')}`/{prod.get('is_sse')})"
            )
        elif not flags.get("groq_vs_prod") and flags.get("gemini_vs_prod"):
            notable_flips.append(
                f"**groq breaks gemini↔prod agree** — {title}: "
                f"prod=`{prod.get('sse_rating')}` → groq=`{groq.get('sse_rating')}`"
            )
        elif flags.get("groq_vs_prod") and not flags.get("gemini_vs_prod"):
            notable_flips.append(
                f"**groq recovers vs prod where gemini differed** — {title}: "
                f"prod=`{prod.get('sse_rating')}` gemini=`{gem.get('sse_rating')}` "
                f"groq=`{groq.get('sse_rating')}`"
            )

    groq_successes = sum(
        1
        for r in reports
        if str((r.get("rerun") or {}).get("provider") or "") == "groq"
    )
    erred = sum(1 for r in reports if (r.get("rerun") or {}).get("error"))

    # Consistency verdict
    g_rating = int(gem_vs_prod_rating["matches"])
    gr_rating = int(groq_vs_prod_rating["matches"])
    gr_gem = int(groq_vs_gem_rating["matches"])
    if gr_gem >= 8 and abs(gr_rating - g_rating) <= 1:
        consistency = (
            "Yes — Groq+Tavily is about as consistent as Gemini+Tavily: "
            f"high agreement with Gemini ({groq_vs_gem_both['frac']} both) and "
            f"similar prod rating match ({groq_vs_prod_rating['frac']} vs Gemini's "
            f"{gem_vs_prod_rating['frac']})."
        )
    elif gr_gem >= 7:
        consistency = (
            "Mostly — Groq largely tracks Gemini "
            f"({groq_vs_gem_rating['frac']} rating) but diverges on a few jobs; "
            f"prod rating match {groq_vs_prod_rating['frac']} vs Gemini "
            f"{gem_vs_prod_rating['frac']}."
        )
    else:
        consistency = (
            "No — Groq and Gemini disagree on too many ratings "
            f"({groq_vs_gem_rating['frac']}); treat Groq+Tavily as less interchangeable "
            "with Gemini+Tavily on this set."
        )

    verdict = (
        f"{consistency} "
        f"Groq completions: {groq_successes}/{n}; errors: {erred}. "
        f"Providers used: {providers_used}."
    )
    headline = (
        f"Groq↔prod rating **{groq_vs_prod_rating['frac']}** · "
        f"Groq↔Gemini rating **{groq_vs_gem_rating['frac']}** · "
        f"Gemini↔prod rating **{gem_vs_prod_rating['frac']}** (prior 6/10)."
    )

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": "tavily_always_force_grounding_groq_only",
        "dry_run": True,
        "wrote_to_db": False,
        "setup": {
            "gemini_key_in_process": gemini_in_proc,
            "gemini_was_in_env": _GEMINI_WAS_SET,
            "cerebras_key_in_process": cerebras_in_proc,
            "cerebras_was_in_env": _CEREBRAS_WAS_SET,
            "use_google_search_grounding": google_search_on,
            "tavily_available": tavily_ok,
            "provider_chain": " → ".join(chain_names),
            "groq_only": groq_only,
            "groq_first": groq_first,
            "out_tag": args.out_tag,
        },
        "job_ids": job_ids,
        "headline": headline,
        "match_rates": match_rates,
        "verdict": verdict,
        "notable_flips": notable_flips,
        "providers_used": providers_used,
        "failures": failures,
        "jobs": reports,
    }
    write_report(payload)
    print("\n======== HEADLINE ========")
    print(headline)
    print("\n======== VERDICT ========")
    print(verdict)
    print("\n======== MATCH RATES ========")
    print(json.dumps(match_rates, indent=2))
    print(f"\nReport: {REPORT_MD}")
    print(f"JSON:   {REPORT_JSON}")
    print(f"Log:    {LOG_PATH}")


if __name__ == "__main__":
    main()
