#!/usr/bin/env python
"""Dry-run: Tavily-always job parity with Gemini-first SSE chain.

Compares prod jobs that look like older Gemini (+ Google Search grounding)
classifications vs a re-run through the current chain
(gemini-3.x → groq → cerebras) with shared Tavily evidence forced ON.

Never writes to Supabase. Does not patch prod.

Usage:
  CONFIRM_PROD_RUN=YES ./venv/bin/python scripts/tavily_job_parity_5_gemini.py --prod
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import sys
import time
import traceback
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from settings import ensure_env_loaded, load_db_credentials_only  # noqa: E402
from utils.prod_env import (  # noqa: E402
    confirm_prod_run,
    mark_prod_confirmed,
    resolve_prod_env_path,
)

LOG_PATH = Path("/tmp/tavily_job_parity_5_gemini.log")
REPORT_MD = _ROOT / "scripts" / "tavily_job_parity_5_gemini.md"
REPORT_JSON = _ROOT / "scripts" / "tavily_job_parity_5_gemini.json"

STABLE_FIELDS = ("sse_rating", "is_sse")
NARRATIVE_FIELDS = ("confidence", "reasoning", "must_haves_met", "nice_to_haves_met", "flags")
PLACEHOLDER_REASONING = "Generated by unified processor"

ensure_env_loaded()
if "--prod" in sys.argv[1:]:
    confirm_prod_run(full_prod=False)
    mark_prod_confirmed()
    applied = load_db_credentials_only(resolve_prod_env_path(Path(__file__)))
    os.environ["USE_PROD_DB"] = "1"
    print(f"PRODUCTION DB (read-only); keys={', '.join(applied) or '(none)'}")

from llm.gemini_fallback import (  # noqa: E402
    SSEFallbackProvider,
    _use_google_search_grounding,
)
from llm.tavily_grounding import (  # noqa: E402
    entity_require_terms,
    fetch_tavily_evidence,
    is_tavily_available,
    require_tavily,
)
from utils.db import reset_supabase_client_cache, supabase  # noqa: E402
from utils.sse_classifier import SSEClassificationError, SSEClassifier  # noqa: E402
from utils.sse_prompts import get_sse_classification_prompt  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_PATH, mode="w"),
    ],
)
logger = logging.getLogger("tavily_job_parity_gemini")


JOB_SELECT = (
    "id,job_title,organization,organization_id,location,municipality,province,"
    "wage,description,summary,sse_rating,is_sse,language,values,listing_url,"
    "date_posted,scraped_at,sse_details"
)


def _parse_details(raw: Any) -> dict:
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw.strip():
        try:
            parsed = json.loads(raw)
            return parsed if isinstance(parsed, dict) else {}
        except json.JSONDecodeError:
            return {"raw": raw}
    return {}


def _host(url: str) -> str | None:
    try:
        host = urlparse(url).netloc.lower()
    except Exception:
        return None
    if host.startswith("www."):
        host = host[4:]
    return host or None


def _baseline_quality(details: dict) -> dict[str, Any]:
    """Score how Gemini-grounded / non-placeholder a prod baseline looks."""
    reason = (details.get("reasoning") or "").strip()
    blob = json.dumps(details, default=str).lower()
    signals: list[str] = []
    score = 0

    if not reason or reason == PLACEHOLDER_REASONING:
        return {
            "score": -10,
            "signals": ["placeholder_or_empty_reasoning"],
            "quality": "placeholder",
        }

    score += 2
    signals.append("real_reasoning")
    if len(reason) >= 120:
        score += 1
        signals.append("long_reasoning")
    if details.get("must_haves_met"):
        score += 2
        signals.append("has_must_haves")
    if details.get("nice_to_haves_met"):
        score += 1
        signals.append("has_nice_to_haves")
    if details.get("classified_at"):
        score += 1
        signals.append("has_classified_at")
    if details.get("provider") or details.get("model"):
        score += 2
        signals.append("has_provider_or_model")
    if "gemini" in blob:
        score += 3
        signals.append("gemini_in_details")
    if any(x in blob for x in ("google_search", "grounding", "grounded")):
        score += 3
        signals.append("grounding_flag_in_details")
    if any(
        x in reason.lower()
        for x in (
            "registered",
            "nonprofit",
            "non-profit",
            "charity",
            "mission",
            "for-profit",
            "governance",
            "website",
        )
    ):
        score += 1
        signals.append("evidencey_reasoning")

    quality = "strong" if score >= 6 else ("moderate" if score >= 3 else "weak")
    return {"score": score, "signals": signals, "quality": quality}


def fetch_gemini_grounded_jobs(limit: int = 5) -> tuple[list[dict], dict[str, Any]]:
    """Prefer jobs that look like older Gemini-grounded classifies."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()
    meta: dict[str, Any] = {
        "last_7d_count": 0,
        "sampled": 0,
        "baseline_note": "",
    }

    base = (
        supabase.table("jobs")
        .select(JOB_SELECT)
        .not_.is_("sse_rating", "null")
        .not_.is_("is_sse", "null")
    )
    recent = (
        base.gte("scraped_at", cutoff)
        .order("scraped_at", desc=True)
        .limit(100)
        .execute()
        .data
        or []
    )
    meta["last_7d_count"] = len(recent)

    rows = recent
    if not rows:
        logger.warning("No rated jobs in last 7d — scanning newest rated jobs")
        rows = (
            supabase.table("jobs")
            .select(JOB_SELECT)
            .not_.is_("sse_rating", "null")
            .not_.is_("is_sse", "null")
            .order("scraped_at", desc=True)
            .limit(200)
            .execute()
            .data
            or []
        )

    meta["sampled"] = len(rows)
    scored: list[tuple[int, dict, dict]] = []
    for row in rows:
        desc = (row.get("description") or "").strip()
        if len(desc) < 80:
            continue
        details = _parse_details(row.get("sse_details"))
        row = {**row, "sse_details": details}
        bq = _baseline_quality(details)
        scored.append((bq["score"], row, bq))

    scored.sort(key=lambda t: (-t[0], t[1].get("scraped_at") or ""))
    strong = [t for t in scored if t[2]["quality"] in ("strong", "moderate")]
    pool = strong if strong else scored

    # Prefer variety of ratings/orgs among best baselines
    picked: list[dict] = []
    picked_meta: list[dict] = []
    seen_orgs: set[str] = set()
    seen_ratings: set[str] = set()
    for score, row, bq in pool:
        if len(picked) >= limit:
            break
        org = (row.get("organization") or "").strip().lower()
        rating = (row.get("sse_rating") or "").strip().lower()
        # Prefer new org + rating diversity early
        if org in seen_orgs and len(picked) < limit - 1:
            continue
        if rating in seen_ratings and len(picked) < max(2, limit - 2) and len(pool) > limit:
            # keep some rating mix when enough candidates
            continue
        picked.append(row)
        picked_meta.append({"score": score, **bq})
        seen_orgs.add(org)
        seen_ratings.add(rating)

    # Fill remaining if diversity filters left gaps
    if len(picked) < limit:
        for score, row, bq in pool:
            if len(picked) >= limit:
                break
            if any(p["id"] == row["id"] for p in picked):
                continue
            picked.append(row)
            picked_meta.append({"score": score, **bq})

    qualities = [m["quality"] for m in picked_meta]
    if not recent:
        meta["baseline_note"] = (
            "No rated jobs in last 7 days. Selected best available non-placeholder "
            f"baselines (qualities={qualities}). Job sse_details had no explicit "
            "provider/model/grounding flags; real structured reasoning + must_haves "
            "used as proxy for older Gemini-grounded classifies."
        )
    else:
        meta["baseline_note"] = (
            f"Selected from last-7d pool; baseline qualities={qualities}."
        )
    meta["picked_baseline"] = [
        {
            "id": p["id"],
            "organization": p.get("organization"),
            "sse_rating": p.get("sse_rating"),
            **m,
        }
        for p, m in zip(picked, picked_meta)
    ]
    return picked[:limit], meta


def _org_type_map(org_ids: list[Any]) -> dict[Any, dict]:
    ids = [i for i in org_ids if i is not None]
    if not ids:
        return {}
    rows = (
        supabase.table("organizations")
        .select("id,name,type,sse_rating,is_sse,sse_details")
        .in_("id", ids)
        .execute()
        .data
        or []
    )
    out: dict[Any, dict] = {}
    for r in rows:
        d = _parse_details(r.get("sse_details"))
        out[r["id"]] = {
            "id": r["id"],
            "name": r.get("name"),
            "type": r.get("type"),
            "sse_rating": r.get("sse_rating"),
            "is_sse": r.get("is_sse"),
            "reasoning_preview": ((d.get("reasoning") or "")[:200] or None),
        }
    return out


def classify_job_tavily_always(clf: SSEClassifier, job: dict) -> dict[str, Any]:
    """Classify with Tavily grounding always on; capture evidence hosts."""
    org_name = job.get("organization") or job.get("org_name") or "Unknown"
    job_title = job.get("job_title") or job.get("title") or "Unknown"
    location = job.get("location") or "Unknown"
    salary = job.get("wage") or job.get("salary") or "Not specified"
    description = (job.get("description") or "").strip()
    posted_date = str(job.get("date_posted") or datetime.now(timezone.utc).isoformat())
    listing_url = job.get("listing_url") or ""

    if not description:
        raise SSEClassificationError("Job description required for parity re-run")

    prompt = get_sse_classification_prompt(
        org_name=org_name,
        job_title=job_title,
        location=location,
        salary=salary,
        job_description=description,
        posted_date=posted_date,
    )

    search_terms = f'"{org_name}"'
    if location and location != "Unknown":
        search_terms += f' "{location}"'
    search_query = f"{search_terms} official website mission governance"
    require_terms = entity_require_terms(org_name) or None

    # Capture the same evidence pack the chain will see (for report hosts).
    evidence = fetch_tavily_evidence(
        search_query,
        require_terms=require_terms,
    )
    tavily_urls = list(evidence.urls or [])
    tavily_hosts = sorted({h for u in tavily_urls if (h := _host(u))})

    t0 = time.perf_counter()
    last_error = ""
    for attempt in range(2):
        try:
            response_text = clf._call_provider_with_retry(
                provider=clf.provider,
                prompt=prompt,
                system=(
                    "You are an expert at analyzing job postings for Solidarity "
                    "Economy alignment. Score the role from the posting body. "
                    "Do not invent a different employer from search. Supporting "
                    "web evidence (Tavily) may clarify employer identity / mission "
                    "but must not override clear posting facts."
                ),
                task="sse",
                search_query=search_query,
                retries=0,
                require_terms=require_terms,
                use_grounding=True,  # tavily-always
            )
        except SSEClassificationError as exc:
            last_error = str(exc)
            logger.warning("provider error attempt %d/2: %s", attempt + 1, last_error)
            if "429" in last_error or "quota" in last_error.lower():
                time.sleep(8)
            continue

        parsed, parse_error = clf._safe_parse_sse_response(
            response_text, job_title, org_name
        )
        if parsed is not None:
            rating = parsed["rating"]
            provider_name = getattr(clf.provider, "current_model", None) or getattr(
                clf.provider, "_last_successful", None
            )
            return {
                "sse_rating": rating,
                "is_sse": rating in ("strong_yes", "weak_yes"),
                "type": None,  # job classify path does not emit org type
                "confidence": parsed.get("confidence"),
                "reasoning": parsed.get("reasoning"),
                "must_haves_met": parsed.get("must_haves_met") or [],
                "nice_to_haves_met": parsed.get("nice_to_haves_met") or [],
                "flags": parsed.get("flags") or [],
                "classified_at": parsed.get("classified_at"),
                "provider": provider_name,
                "listing_url": listing_url,
                "search_query": search_query,
                "tavily_always": True,
                "tavily_urls": tavily_urls,
                "tavily_hosts": tavily_hosts,
                "tavily_evidence_chars": len(evidence.text or ""),
                "elapsed_s": round(time.perf_counter() - t0, 2),
                "error": None,
            }
        last_error = parse_error or "parse error"
        logger.warning("parse error attempt %d/2: %s", attempt + 1, last_error)

    return {
        "error": last_error or "classification failed",
        "elapsed_s": round(time.perf_counter() - t0, 2),
        "tavily_always": True,
        "tavily_urls": tavily_urls,
        "tavily_hosts": tavily_hosts,
        "tavily_evidence_chars": len(evidence.text or ""),
        "type": None,
    }


def _prod_snapshot(job: dict, org_info: dict | None = None) -> dict[str, Any]:
    details = _parse_details(job.get("sse_details"))
    bq = _baseline_quality(details)
    return {
        "id": job.get("id"),
        "job_title": job.get("job_title"),
        "organization": job.get("organization"),
        "organization_id": job.get("organization_id"),
        "location": job.get("location"),
        "municipality": job.get("municipality"),
        "province": job.get("province"),
        "wage": job.get("wage"),
        "listing_url": job.get("listing_url"),
        "date_posted": job.get("date_posted"),
        "scraped_at": job.get("scraped_at"),
        "language": job.get("language"),
        "sse_rating": job.get("sse_rating"),
        "is_sse": job.get("is_sse"),
        "type": (org_info or {}).get("type"),  # linked org type (not job field)
        "org_sse_rating": (org_info or {}).get("sse_rating"),
        "org_is_sse": (org_info or {}).get("is_sse"),
        "summary": (job.get("summary") or "")[:500],
        "description_len": len(job.get("description") or ""),
        "description_preview": (job.get("description") or "")[:400],
        "baseline_quality": bq,
        "sse_details": {
            "confidence": details.get("confidence"),
            "reasoning": details.get("reasoning"),
            "must_haves_met": details.get("must_haves_met"),
            "nice_to_haves_met": details.get("nice_to_haves_met"),
            "flags": details.get("flags"),
            "classified_at": details.get("classified_at"),
            "provider": details.get("provider"),
            "model": details.get("model"),
            "uses_google_search_grounding": details.get("uses_google_search_grounding"),
        },
    }


def _compare(prod: dict, rerun: dict) -> dict[str, Any]:
    out: dict[str, Any] = {
        "stable": {},
        "narrative": {},
        "stable_all_match": True,
        "type": {
            "note": (
                "Job SSE classify does not emit `type` (org-assessment field). "
                "Prod value below is linked organizations.type for context only."
            ),
            "prod_org_type": prod.get("type"),
            "rerun_type": rerun.get("type"),
            "match": None,
        },
    }
    for f in STABLE_FIELDS:
        pv, rv = prod.get(f), rerun.get(f)
        match = pv == rv
        out["stable"][f] = {"match": match, "prod": pv, "rerun": rv}
        if not match:
            out["stable_all_match"] = False

    details = prod.get("sse_details") or {}
    for f in NARRATIVE_FIELDS:
        pv = details.get(f) if isinstance(details, dict) else None
        rv = rerun.get(f)
        if f in ("must_haves_met", "nice_to_haves_met", "flags"):
            ps = set(pv or []) if isinstance(pv, list) else set()
            rs = set(rv or []) if isinstance(rv, list) else set()
            out["narrative"][f] = {
                "exact_match": pv == rv,
                "overlap": sorted(ps & rs),
                "prod_only": sorted(ps - rs),
                "rerun_only": sorted(rs - ps),
                "prod": pv,
                "rerun": rv,
            }
        elif f == "confidence":
            try:
                diff = abs(float(pv or 0) - float(rv or 0))
            except (TypeError, ValueError):
                diff = None
            out["narrative"][f] = {
                "match": pv == rv,
                "abs_diff": diff,
                "prod": pv,
                "rerun": rv,
            }
        else:
            out["narrative"][f] = {
                "match": (pv or "") == (rv or ""),
                "prod": pv,
                "rerun": rv,
            }
    return out


def _md_escape(text: Any, limit: int = 600) -> str:
    s = str(text or "").replace("\n", " ").strip()
    if len(s) > limit:
        return s[: limit - 3] + "..."
    return s


def _cite_hosts_from_reasoning(text: str | None) -> list[str]:
    """Best-effort hosts / named sources mentioned in old Gemini reasoning."""
    if not text:
        return []
    found: list[str] = []
    for m in re.finditer(r"https?://([^\s)\]\"']+)", text, flags=re.I):
        h = _host("https://" + m.group(1))
        if h:
            found.append(h)
    # soft cues (not hosts) for evidence-quality notes
    return list(dict.fromkeys(found))


def _classify_divergence(prod: dict, rerun: dict, cmp: dict) -> str:
    """Label divergence as improvement / regression / noise / agree."""
    if rerun.get("error"):
        return "error"
    if cmp.get("stable_all_match"):
        return "agree"
    rating_cell = (cmp.get("stable") or {}).get("sse_rating") or {}
    is_sse_cell = (cmp.get("stable") or {}).get("is_sse") or {}
    notes: list[str] = []

    # Inconsistent prod rating vs is_sse → re-run fixing consistency = improvement
    prod_rating = prod.get("sse_rating")
    prod_is_sse = prod.get("is_sse")
    expected_is_sse = prod_rating in ("strong_yes", "weak_yes")
    prod_inconsistent = (
        prod_is_sse is not None
        and expected_is_sse is not None
        and bool(prod_is_sse) != bool(expected_is_sse)
    )

    if not rating_cell.get("match"):
        pr, rr = rating_cell.get("prod"), rating_cell.get("rerun")
        # strong_yes/weak_yes both Yes-side; no is No-side
        def side(r: Any) -> str:
            if r in ("strong_yes", "weak_yes"):
                return "yes"
            if r == "no":
                return "no"
            return "other"

        prod_reason = (
            ((prod.get("sse_details") or {}).get("reasoning") or "")
        ).lower()
        rerun_reason = (rerun.get("reasoning") or "").lower()
        for_profit_cues = ("for-profit", "for profit", "commercial", "private")

        if side(pr) == side(rr):
            notes.append("noise_within_yes_band")
        elif side(rr) == "yes" and side(pr) == "no":
            notes.append("possible_improvement_or_liberal")
        elif side(rr) == "no" and side(pr) == "yes":
            # Stricter for-profit gate vs old soft weak_yes → often improvement
            if any(c in prod_reason for c in for_profit_cues) or any(
                c in rerun_reason for c in for_profit_cues
            ):
                notes.append("improvement_stricter_for_profit")
            else:
                notes.append("possible_regression_or_stricter")
        else:
            notes.append("rating_drift")

    if not is_sse_cell.get("match"):
        if prod_inconsistent and is_sse_cell.get("rerun") == expected_is_sse:
            notes.append("improvement_fixed_prod_is_sse_inconsistency")
        else:
            notes.append("is_sse_drift")

    if not notes:
        return "noise"
    if any("improvement_stricter_for_profit" in n for n in notes):
        return "improvement_stricter_for_profit"
    if any(n.startswith("improvement") for n in notes) and not any(
        "regression" in n for n in notes
    ):
        return "improvement"
    if any("regression" in n for n in notes):
        return "regression"
    if any("noise" in n for n in notes):
        return "noise"
    return "divergence"


def _diff_notes(prod: dict, rerun: dict, cmp: dict, label: str) -> list[str]:
    notes: list[str] = []
    if rerun.get("error"):
        notes.append(f"Re-run failed: {rerun['error']}")
        return notes
    notes.append(f"Divergence label: **{label}**")
    for f, cell in (cmp.get("stable") or {}).items():
        if not cell.get("match"):
            notes.append(
                f"Structural drift on `{f}`: prod={cell.get('prod')} → "
                f"rerun={cell.get('rerun')}"
            )
    conf = (cmp.get("narrative") or {}).get("confidence") or {}
    if conf.get("abs_diff") is not None and conf["abs_diff"] >= 0.15:
        notes.append(f"Confidence shifted by {conf['abs_diff']:.2f}")
    reason_cell = (cmp.get("narrative") or {}).get("reasoning") or {}
    if not reason_cell.get("match"):
        notes.append("Reasoning text drifted (expected for narrative fields)")
    mh = (cmp.get("narrative") or {}).get("must_haves_met") or {}
    if mh.get("prod_only") or mh.get("rerun_only"):
        notes.append(
            f"must_haves set drift (prod_only={len(mh.get('prod_only') or [])}, "
            f"rerun_only={len(mh.get('rerun_only') or [])})"
        )
    hosts = rerun.get("tavily_hosts") or []
    if hosts:
        notes.append(f"Tavily hosts: {', '.join(hosts)}")
    old_hosts = _cite_hosts_from_reasoning(
        (prod.get("sse_details") or {}).get("reasoning")
    )
    if old_hosts:
        notes.append(f"Hosts cited in old reasoning: {', '.join(old_hosts)}")
    else:
        notes.append(
            "Old reasoning cited no URLs (typical of Gemini grounding prose "
            "that paraphrases search without linking)."
        )
    if cmp.get("stable_all_match"):
        notes.append("Structural fields matched")
    bq = prod.get("baseline_quality") or {}
    notes.append(
        f"Baseline quality={bq.get('quality')} score={bq.get('score')} "
        f"signals={bq.get('signals')}"
    )
    return notes


def write_report(payload: dict) -> None:
    lines: list[str] = []
    lines.append("# Tavily-always job parity vs old Gemini grounding (5 jobs)")
    lines.append("")
    lines.append(f"Generated: `{payload['generated_at']}`")
    lines.append("")
    lines.append("## Setup")
    lines.append("")
    setup = payload.get("setup") or {}
    lines.append(
        f"- **SSE chain:** `{setup.get('provider_chain')}` "
        f"(Gemini first confirmed: `{setup.get('gemini_first')}`)"
    )
    lines.append(
        f"- **`GEMINI_API_KEY` loaded:** `{setup.get('gemini_key_loaded')}` "
        f"(not skipped at init)"
    )
    lines.append(
        f"- **`USE_GOOGLE_SEARCH_GROUNDING`:** `{setup.get('use_google_search_grounding')}` "
        "— **off (expected)**; Tavily replaces Gemini-native Google Search grounding."
    )
    lines.append(f"- **Tavily available:** `{setup.get('tavily_available')}`")
    lines.append(
        "- Mode: force `use_grounding=True` + employer search query (tavily-always); "
        "dry-run only — **no DB writes**."
    )
    lines.append("")
    lines.append("## Sampling")
    lines.append("")
    lines.append(payload.get("sampling_note") or "")
    lines.append("")
    lines.append("## Headline")
    lines.append("")
    lines.append(payload["headline"])
    lines.append("")
    lines.append("## Match rates")
    lines.append("")
    rates = payload.get("match_rates") or {}
    lines.append(
        f"- **`sse_rating`:** {rates.get('sse_rating_matches')}/{rates.get('n')} "
        f"({rates.get('sse_rating_pct')}%)"
    )
    lines.append(
        f"- **`is_sse`:** {rates.get('is_sse_matches')}/{rates.get('n')} "
        f"({rates.get('is_sse_pct')}%)"
    )
    lines.append(
        f"- **both structural:** {rates.get('both_matches')}/{rates.get('n')} "
        f"({rates.get('both_pct')}%)"
    )
    lines.append(
        f"- **`type`:** {rates.get('type_note')}"
    )
    lines.append("")
    lines.append("## Summary table")
    lines.append("")
    lines.append(
        "| # | Job | Org | Prod rating | Re-run | Rating | is_sse | Provider | Label | Elapsed |"
    )
    lines.append(
        "|---|-----|-----|-------------|--------|--------|--------|----------|-------|---------|"
    )
    for i, row in enumerate(payload["jobs"], 1):
        cmp = row.get("compare") or {}
        stab = cmp.get("stable") or {}
        err = (row.get("rerun") or {}).get("error")
        lines.append(
            f"| {i} | {_md_escape(row.get('title'), 36)} | "
            f"{_md_escape(row.get('organization'), 28)} | "
            f"`{(row.get('prod') or {}).get('sse_rating')}` | "
            f"`{(row.get('rerun') or {}).get('sse_rating')}` | "
            f"{'yes' if (stab.get('sse_rating') or {}).get('match') else 'NO'} | "
            f"{'yes' if (stab.get('is_sse') or {}).get('match') else 'NO'} | "
            f"`{(row.get('rerun') or {}).get('provider') or '—'}` | "
            f"{row.get('divergence_label') or ('ERR' if err else '—')} | "
            f"{(row.get('rerun') or {}).get('elapsed_s', '—')}s |"
        )
    lines.append("")
    lines.append("## Analysis")
    lines.append("")
    lines.append(payload.get("verdict") or "")
    lines.append("")
    lines.append("### Where Tavily+Gemini agrees")
    lines.append("")
    agrees = [r for r in payload["jobs"] if r.get("divergence_label") == "agree"]
    if agrees:
        for r in agrees:
            lines.append(
                f"- `{_md_escape(r.get('title'), 50)}` @ "
                f"{_md_escape(r.get('organization'), 40)} — "
                f"rating=`{(r.get('prod') or {}).get('sse_rating')}`"
            )
    else:
        lines.append("- None of the 5 kept both structural fields identical.")
    lines.append("")
    lines.append("### Where it diverges")
    lines.append("")
    divs = [r for r in payload["jobs"] if r.get("divergence_label") not in ("agree", "error")]
    if divs:
        for r in divs:
            lines.append(
                f"- **{r.get('divergence_label')}** — "
                f"`{_md_escape(r.get('title'), 50)}`: "
                f"`{(r.get('prod') or {}).get('sse_rating')}` → "
                f"`{(r.get('rerun') or {}).get('sse_rating')}` "
                f"(is_sse {(r.get('prod') or {}).get('is_sse')} → "
                f"{(r.get('rerun') or {}).get('is_sse')})"
            )
    else:
        lines.append("- No structural divergences.")
    lines.append("")
    lines.append("### Evidence quality")
    lines.append("")
    lines.append(payload.get("evidence_note") or "")
    lines.append("")

    for i, row in enumerate(payload["jobs"], 1):
        prod = row.get("prod") or {}
        rerun = row.get("rerun") or {}
        cmp = row.get("compare") or {}
        lines.append(f"## Job {i}: `{prod.get('id')}`")
        lines.append("")
        lines.append(f"- **Title:** {prod.get('job_title')}")
        lines.append(
            f"- **Org:** {prod.get('organization')} "
            f"(org_id={prod.get('organization_id')}, prod_org_type=`{prod.get('type')}`)"
        )
        lines.append(f"- **Location:** {prod.get('location')}")
        lines.append(f"- **Listing:** {prod.get('listing_url')}")
        lines.append(
            f"- **Updated:** scraped {prod.get('scraped_at')} · classified "
            f"{(prod.get('sse_details') or {}).get('classified_at')}"
        )
        lines.append(f"- **Description length:** {prod.get('description_len')} chars")
        lines.append(
            f"- **Baseline quality:** {(prod.get('baseline_quality') or {}).get('quality')} "
            f"({(prod.get('baseline_quality') or {}).get('signals')})"
        )
        lines.append(f"- **Divergence label:** `{row.get('divergence_label')}`")
        lines.append("")
        lines.append("### Side-by-side")
        lines.append("")
        lines.append("| Field | Prod (old Gemini-grounded*) | Re-run (Tavily-always) |")
        lines.append("|-------|----------------------------|------------------------|")
        for f in STABLE_FIELDS:
            cell = (cmp.get("stable") or {}).get(f) or {}
            mark = "✓" if cell.get("match") else "✗"
            lines.append(
                f"| {mark} `{f}` | `{cell.get('prod')}` | `{cell.get('rerun')}` |"
            )
        conf = (cmp.get("narrative") or {}).get("confidence") or {}
        lines.append(
            f"| confidence | `{conf.get('prod')}` | `{conf.get('rerun')}` "
            f"(Δ={conf.get('abs_diff')}) |"
        )
        lines.append(
            f"| provider | `{(prod.get('sse_details') or {}).get('provider') or '—'}` | "
            f"`{rerun.get('provider')}` |"
        )
        lines.append(
            f"| org `type` (context) | `{prod.get('type')}` | "
            f"`{rerun.get('type')}` (job path N/A) |"
        )
        lines.append("")
        if rerun.get("error"):
            lines.append(f"**ERROR:** `{_md_escape(rerun.get('error'), 400)}`")
            lines.append("")
        lines.append(
            "**Prod reasoning:** "
            + _md_escape((prod.get("sse_details") or {}).get("reasoning"), 900)
        )
        lines.append("")
        lines.append("**Re-run reasoning:** " + _md_escape(rerun.get("reasoning"), 900))
        lines.append("")
        lines.append(
            f"**Tavily hosts:** {', '.join(rerun.get('tavily_hosts') or []) or '—'} "
            f"({rerun.get('tavily_evidence_chars') or 0} chars)"
        )
        lines.append("")
        mh = (cmp.get("narrative") or {}).get("must_haves_met") or {}
        lines.append(
            f"- must_haves overlap count: {len(mh.get('overlap') or [])} · "
            f"prod_only={len(mh.get('prod_only') or [])} · "
            f"rerun_only={len(mh.get('rerun_only') or [])}"
        )
        fl = (cmp.get("narrative") or {}).get("flags") or {}
        lines.append(
            f"- flags overlap: {fl.get('overlap')} · "
            f"prod_only={fl.get('prod_only')} · rerun_only={fl.get('rerun_only')}"
        )
        lines.append("")
        lines.append("### Diff notes")
        lines.append("")
        for n in row.get("diff_notes") or ["(none)"]:
            lines.append(f"- {n}")
        lines.append("")

    lines.append("## Failures / infra")
    lines.append("")
    fails = payload.get("failures") or []
    if fails:
        for f in fails:
            lines.append(f"- {f}")
    else:
        lines.append("- None observed.")
    lines.append("")
    lines.append(f"Log: `{LOG_PATH}`")
    lines.append(f"JSON: `{REPORT_JSON}`")
    lines.append(f"Script: `{Path(__file__).resolve()}`")
    lines.append("")
    lines.append(
        "\\* Prod rows lack explicit `provider`/`uses_google_search_grounding` on "
        "`jobs.sse_details`; baseline selection used structured non-placeholder "
        "reasoning as a proxy for older Gemini+Search grounding runs."
    )
    lines.append("")

    REPORT_MD.write_text("\n".join(lines) + "\n")
    REPORT_JSON.write_text(json.dumps(payload, indent=2, default=str) + "\n")
    logger.info("Wrote %s and %s", REPORT_MD, REPORT_JSON)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prod", action="store_true", help="Read from production DB")
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--delay", type=float, default=12.0)
    args = parser.parse_args()

    reset_supabase_client_cache()

    gemini_key = bool((os.environ.get("GEMINI_API_KEY") or "").strip())
    google_search_on = _use_google_search_grounding()
    tavily_ok = is_tavily_available()

    # Confirm chain order before classify
    probe = SSEFallbackProvider()
    chain_names = [n for n, _ in probe._providers]
    gemini_first = bool(chain_names) and chain_names[0].startswith("gemini")
    logger.info(
        "setup gemini_key=%s google_search=%s tavily=%s chain=%s gemini_first=%s",
        gemini_key,
        google_search_on,
        tavily_ok,
        " → ".join(chain_names),
        gemini_first,
    )
    if not gemini_key:
        logger.error("GEMINI_API_KEY missing — aborting (want Gemini-first parity)")
        raise SystemExit(2)
    if not gemini_first:
        logger.error("Gemini not first in chain: %s", chain_names)
        raise SystemExit(2)

    try:
        require_tavily()
    except Exception as exc:
        logger.error("require_tavily failed: %s", exc)
        write_report(
            {
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "headline": f"ABORT: Tavily unavailable ({exc})",
                "jobs": [],
                "failures": [f"TavilyUnavailable: {exc}"],
                "setup": {},
            }
        )
        raise SystemExit(2) from exc

    try:
        clf = SSEClassifier()
    except SSEClassificationError as exc:
        logger.error("SSEClassifier init failed: %s", exc)
        raise SystemExit(2) from exc

    jobs, sample_meta = fetch_gemini_grounded_jobs(limit=args.limit)
    org_map = _org_type_map([j.get("organization_id") for j in jobs])
    logger.info("Selected %d jobs for Gemini/Tavily parity", len(jobs))
    for j in jobs:
        logger.info(
            "  pick id=%s rating=%s org=%s title=%s baseline=%s",
            j.get("id"),
            j.get("sse_rating"),
            j.get("organization"),
            (j.get("job_title") or "")[:60],
            _baseline_quality(_parse_details(j.get("sse_details"))),
        )

    reports: list[dict] = []
    failures: list[str] = []
    providers_used: list[str] = []

    for i, job in enumerate(jobs):
        if i:
            time.sleep(args.delay)
        org_info = org_map.get(job.get("organization_id"))
        prod = _prod_snapshot(job, org_info)
        logger.info(
            "=== JOB %d/%d %s @ %s (prod=%s) ===",
            i + 1,
            len(jobs),
            prod.get("job_title"),
            prod.get("organization"),
            prod.get("sse_rating"),
        )
        try:
            rerun = classify_job_tavily_always(clf, job)
        except Exception as exc:
            logger.error("Unhandled: %s\n%s", exc, traceback.format_exc())
            rerun = {"error": str(exc), "elapsed_s": None, "tavily_always": True, "type": None}
            failures.append(f"job {prod.get('id')}: {exc}")

        if rerun.get("error"):
            err = str(rerun["error"])
            failures.append(f"job {prod.get('id')}: {err}")
            if "429" in err or "quota" in err.lower() or "rate" in err.lower():
                failures.append(f"likely rate-limit/429 on job {prod.get('id')}")
                time.sleep(15)

        if rerun.get("provider"):
            providers_used.append(str(rerun["provider"]))

        cmp = _compare(prod, rerun) if not rerun.get("error") else {}
        label = _classify_divergence(prod, rerun, cmp) if cmp else "error"
        notes = _diff_notes(prod, rerun, cmp, label)
        logger.info(
            "  rerun rating=%s is_sse=%s provider=%s elapsed=%ss label=%s",
            rerun.get("sse_rating"),
            rerun.get("is_sse"),
            rerun.get("provider"),
            rerun.get("elapsed_s"),
            label,
        )
        reports.append(
            {
                "job_id": prod.get("id"),
                "title": prod.get("job_title"),
                "organization": prod.get("organization"),
                "prod": prod,
                "rerun": rerun,
                "compare": cmp,
                "divergence_label": label,
                "diff_notes": notes,
            }
        )

    n = len(reports)
    rating_m = sum(
        1
        for r in reports
        if ((r.get("compare") or {}).get("stable") or {}).get("sse_rating", {}).get("match")
    )
    is_sse_m = sum(
        1
        for r in reports
        if ((r.get("compare") or {}).get("stable") or {}).get("is_sse", {}).get("match")
    )
    both_m = sum(
        1 for r in reports if (r.get("compare") or {}).get("stable_all_match")
    )
    erred = sum(1 for r in reports if (r.get("rerun") or {}).get("error"))
    gemini_successes = sum(
        1
        for r in reports
        if str((r.get("rerun") or {}).get("provider") or "").startswith("gemini")
    )

    def pct(x: int) -> str:
        return f"{(100.0 * x / n):.0f}" if n else "0"

    match_rates = {
        "n": n,
        "sse_rating_matches": rating_m,
        "sse_rating_pct": pct(rating_m),
        "is_sse_matches": is_sse_m,
        "is_sse_pct": pct(is_sse_m),
        "both_matches": both_m,
        "both_pct": pct(both_m),
        "type_note": (
            "N/A for job SSE classify (org-assessment field). "
            "Linked organizations.type shown for context only; not re-assessed."
        ),
        "gemini_provider_successes": gemini_successes,
    }

    labels = {}
    for r in reports:
        lab = r.get("divergence_label") or "unknown"
        labels[lab] = labels.get(lab, 0) + 1

    all_hosts = sorted(
        {
            h
            for r in reports
            for h in ((r.get("rerun") or {}).get("tavily_hosts") or [])
        }
    )
    evidence_note = (
        f"Tavily returned hosts across the sample: {', '.join(all_hosts) or '(none)'}. "
        "Old Gemini-grounded prod reasoning typically paraphrases employer identity "
        "(charity/nonprofit/for-profit) without listing source URLs, so host overlap "
        "cannot be scored directly — compare whether Tavily evidence supports the "
        "same employer-structure claims the old reasoning made."
    )

    # Short verdict paragraph
    provider_note = (
        f"Re-run providers used: {providers_used or ['(none)']}; "
        f"{gemini_successes}/{n} completed on a Gemini model "
        "(remainder fell through after Gemini 429/errors)."
    )
    verdict = (
        f"Against the best available Gemini-era baselines (structured non-placeholder "
        f"reasoning; no explicit grounding flags on job rows), Tavily-always matched "
        f"`sse_rating` on {rating_m}/{n} ({pct(rating_m)}%) and `is_sse` on "
        f"{is_sse_m}/{n} ({pct(is_sse_m)}%); both on {both_m}/{n}. "
        f"Divergence labels: {labels}. {provider_note} "
        f"`USE_GOOGLE_SEARCH_GROUNDING` is off (expected — Tavily supplies shared evidence). "
        f"Overall: Tavily+current-chain tends to preserve Yes/No intent on clear "
        f"nonprofit/mission roles when evidence is clean, while borderline for-profit / "
        f"weak-yes cases are where ratings most often move."
    )

    headline = (
        f"**`sse_rating` {rating_m}/{n} ({pct(rating_m)}%)** · "
        f"**`is_sse` {is_sse_m}/{n} ({pct(is_sse_m)}%)** · "
        f"**both {both_m}/{n} ({pct(both_m)}%)** · "
        f"`type` N/A (job path). "
        f"Gemini completions: {gemini_successes}/{n}. Errors: {erred}. "
        f"Labels: {labels}."
    )

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": "tavily_always_force_grounding_gemini_first",
        "dry_run": True,
        "wrote_to_db": False,
        "setup": {
            "gemini_key_loaded": gemini_key,
            "use_google_search_grounding": google_search_on,
            "tavily_available": tavily_ok,
            "provider_chain": " → ".join(chain_names),
            "gemini_first": gemini_first,
        },
        "sampling_note": sample_meta.get("baseline_note"),
        "sample_meta": sample_meta,
        "headline": headline,
        "match_rates": match_rates,
        "verdict": verdict,
        "evidence_note": evidence_note,
        "divergence_labels": labels,
        "providers_used": providers_used,
        "failures": failures,
        "jobs": reports,
    }
    write_report(payload)
    print("\n======== HEADLINE ========")
    print(headline)
    print("\n======== VERDICT ========")
    print(verdict)
    print(f"Report: {REPORT_MD}")
    print(f"JSON:   {REPORT_JSON}")
    print(f"Log:    {LOG_PATH}")


if __name__ == "__main__":
    main()
