/**
 * Validates backup JSON files against the generated database.types.ts schema.
 *
 * For each backup_<schema>_<table>.json file, checks:
 *   - No extra columns beyond what the Insert type allows
 *   - All required (non-optional) Insert columns are present
 *
 * Uses the TypeScript compiler API to parse database.types.ts — no fragile
 * regex on generated code.
 *
 * Run: npx tsx supabase/scripts/check-backups-schema.ts
 */
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

const typesPath = path.resolve(__dirname, "..", "src", "database.types.ts");
const backupsDir = path.resolve(__dirname, "..", "backups");

if (!fs.existsSync(typesPath)) {
  console.error(
    "database.types.ts not found — run `npm run types:supabase` first.",
  );
  process.exit(2);
}

if (!fs.existsSync(backupsDir)) {
  console.error("Backups directory not found.");
  process.exit(2);
}

// ---------------------------------------------------------------------------
// Parse Insert keys via TypeScript compiler API
// ---------------------------------------------------------------------------

/**
 * Walk Database["public"]["Tables"][table]["Insert"] and return each property
 * name with its optionality. Returns null if the table is not found.
 */
function parseInsertKeys(
  table: string,
): { name: string; optional: boolean }[] | null {
  const program = ts.createProgram([typesPath], { noEmit: true });
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(typesPath);
  if (!sourceFile) return null;

  // Resolve: Database -> public -> Tables -> <table> -> Insert
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  if (!moduleSymbol) return null;

  const exports = checker.getExportsOfModule(moduleSymbol);
  const dbExport = exports.find((s) => s.getName() === "Database");
  if (!dbExport) return null;

  const dbType = checker.getDeclaredTypeOfSymbol(dbExport);
  const publicProp = dbType.getProperty("public");
  if (!publicProp) return null;

  const publicType = checker.getTypeOfSymbol(publicProp);
  const tablesProp = publicType.getProperty("Tables");
  if (!tablesProp) return null;

  const tablesType = checker.getTypeOfSymbol(tablesProp);
  const tableProp = tablesType.getProperty(table);
  if (!tableProp) return null;

  const tableType = checker.getTypeOfSymbol(tableProp);
  const insertProp = tableType.getProperty("Insert");
  if (!insertProp) return null;

  const insertType = checker.getTypeOfSymbol(insertProp);
  return insertType.getProperties().map((prop) => ({
    name: prop.getName(),
    optional: !!(prop.flags & ts.SymbolFlags.Optional),
  }));
}

// ---------------------------------------------------------------------------
// Columns generated by the DB that are never part of Insert payloads
// ---------------------------------------------------------------------------
const GENERATED_COLUMN_PATTERNS = [
  /^fts(?:_[a-z]{2,})?$/i,
  /_fts$/i,
  /search_vector$/i,
  /^has_compensation$/i,
  /^ideal_work_environment$/i,
];

function isGeneratedColumn(col: string): boolean {
  return GENERATED_COLUMN_PATTERNS.some((rx) => rx.test(col));
}

// ---------------------------------------------------------------------------
// Main validation loop
// ---------------------------------------------------------------------------

const backupFiles = fs
  .readdirSync(backupsDir)
  .filter((f) => f.startsWith("backup_") && f.endsWith(".json"));

let failed = false;

for (const file of backupFiles) {
  const match = file.match(/^backup_([^_]+)_(.+)\.json$/);
  if (!match) continue;
  const table = match[2];

  const insertKeys = parseInsertKeys(table);
  if (!insertKeys) {
    console.error(
      `Could not find Insert type for table "${table}" in database.types.ts` +
        ` — run \`npm run types:supabase\` to regenerate, or skip "${table}" intentionally.`,
    );
    failed = true;
    continue;
  }

  const allowed = new Set(insertKeys.map((k) => k.name));
  const required = insertKeys.filter((k) => !k.optional).map((k) => k.name);

  const data: unknown = JSON.parse(
    fs.readFileSync(path.resolve(backupsDir, file), "utf8"),
  );
  if (!Array.isArray(data) || data.length === 0) continue;

  const keysInBackup = new Set<string>();
  for (const row of data) {
    if (row && typeof row === "object") {
      Object.keys(row).forEach((k) => keysInBackup.add(k));
    }
  }

  const extra = Array.from(keysInBackup).filter(
    (k) => !allowed.has(k) && !isGeneratedColumn(k),
  );
  if (extra.length > 0) {
    console.error(
      `${file}: contains non-insertable columns: ${extra.join(", ")}`,
    );
    failed = true;
  }

  const missing = required.filter((k) => !keysInBackup.has(k));
  if (missing.length > 0) {
    console.error(
      `${file}: missing required insert columns: ${missing.join(", ")}`,
    );
    failed = true;
  }
}

if (failed) process.exit(1);
console.log("Backups schema check passed.");
