#!/usr/bin/env bash

set -euo pipefail

if ! command -v supabase >/dev/null 2>&1; then
  echo "✗ Supabase CLI is not installed or not on PATH."
  exit 1
fi

PROJECT_REF="${SUPABASE_PROJECT_REF:-}"

if [[ -z "${PROJECT_REF}" && -n "${SUPABASE_URL:-}" ]]; then
  PROJECT_REF="$(printf '%s' "${SUPABASE_URL}" | sed -E 's#^[a-zA-Z]+://##' | cut -d'.' -f1)"
fi

if [[ -z "${PROJECT_REF}" ]]; then
  echo "✗ SUPABASE_PROJECT_REF must be set, or SUPABASE_URL must be present so it can be derived."
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_PATH="${REPO_ROOT}/lib/supabase/database.types.ts"
TMP_FILE="$(mktemp)"

cat <<'EOF' > "${TMP_FILE}"
// Generated from the Supabase public schema.
// Regenerate with: npm run types:supabase
// Do not edit this file by hand.

EOF

supabase gen types typescript --project-id "${PROJECT_REF}" --schema public >> "${TMP_FILE}"

mv "${TMP_FILE}" "${OUTPUT_PATH}"

echo "✓ Wrote ${OUTPUT_PATH}"
