export const JOB_BOARD_TEST_IDS = {
  filtersToggle: 'job-board-filters-toggle',
  postedWithinGroup: 'job-board-posted-within-group',
  workTypeGroup: 'job-board-work-type-group',
  languageGroup: 'job-board-language-group',
  salaryToggle: 'job-board-salary-toggle',
  provinceSection: 'job-board-province-section',
  municipalitySection: 'job-board-municipality-section',
  employmentTypeSection: 'job-board-employment-type-section',
  organizationSection: 'job-board-organization-section',
  sourceSection: 'job-board-source-section',
  localeSwitcher: 'job-board-locale-switcher',
  jobCard: 'job-card',
  paginationSummary: 'job-board-pagination-summary',
  emptyState: 'job-board-empty-state',
  bookmarkButton: 'job-card-bookmark-button',
} as const;
