name: ESLint

on:
  push:
    paths:
      - 'wev-bulletin/**'
  pull_request:
    paths:
      - 'wev-bulletin/**'

defaults:
  run:
    working-directory: wev-bulletin

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: wev-bulletin/package-lock.json
      - run: npm ci
      - run: npm run lint