name: Code Quality

permissions:
  contents: read
  pull-requests: read
  checks: write

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trunk_check:
    name: Trunk Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
